- en/docs/assets/css/theme.css
- en/mkdocs.yml
- en/theme/material/partials/header.html
This PR is to update the initial site content.
This will,
- update the repo details on the mkdocs.yml file.
- add a WIP banner to the site.
> [4.2.0] Update site content

- en/docs/learn/learn-overview.md
This PR is to fix broken links on the Learn Overview page.
> Fix broken links on the Learn Overview page

- en/docs/get-started/quick-start-guide.md
This PR is to update info in JDK type in QSG.
> Update info in JDK type

- README.md
This PR is to update README.md on how to contribute to the MI Documentation.
This will fix https://github.com/wso2/docs-mi/issues/19.
> Add info on contribution to README.md

- en/docs/install-and-setup/install-and-setup-overview.md
This PR is to format the HTML table on `install-and-setup-overiew.md`.
> Format the HTML table

- en/docs/reference/connectors/ldap-connector/ldap-server-configuration.md
$subject
Related to https://github.com/wso2/product-ei/issues/4598
> Introduce new parameter to LDAP Connector search

- en/docs/install-and-setup/install-and-setup-overview.md
- en/docs/learn/examples/file-processing/accessing-windows-share-using-vfs-transport.md
- en/docs/learn/examples/file-processing/mailto-transport-examples.md
- en/docs/learn/examples/file-processing/vfs-transport-examples.md
- en/docs/learn/examples/protocol-switching/switching-from-fix-to-http.md
- en/docs/learn/examples/protocol-switching/switching-from-jms-to-http.md
- en/docs/learn/examples/proxy-service-examples/publishing-a-custom-wsdl.md
- en/docs/learn/examples/rest-api-examples/configuring-non-http-endpoints.md
- en/docs/learn/examples/rest-api-examples/handling-non-matching-resources.md
- en/docs/observe-and-manage/observe-overview.md
This PR is to further modify the content in the MI docs repo.
> Modify the doc space

- en/docs/install-and-setup/setup/transport-configurations/multi-https-transport.md
Porting wso2/docs-ei#2793
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
> Update sslprofile docs- Add xmlns:svns namespace in the parameter section

- en/docs/reference/connectors/kafka-connector/3.0.x/kafka-connector-config.md
- en/docs/reference/connectors/kafka-connector/kafka-connector-config.md
The property is added by https://github.com/wso2-extensions/esb-connector-kafka/pull/33/files
> Link(s) to product …
> Add saslMechanism parameter to Kafka docs

- en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-configuration.md
azure-core-1.41.0.jar is missing in connector setup docs …
> Add missing in Microsoft Azure Storage Connector docs

- en/docs/develop/hot-deployment.md
Readiness prob does not depend on the the hot deployment, therefore, removing the content
> Link(s) to product documentation …
> Remove readiness probe content related to hot deployment

- en/theme/material/main.html
This PR is to remove the WIP banner.
> Remove WIP banner

- en/docs/develop/create-kubernetes-project.md
- en/docs/develop/generate-docker-image.md
- en/docs/develop/integration-development-kickstart.md
- en/docs/develop/intro-integration-development.md
- en/docs/get-started/development-kickstart.md
- en/docs/get-started/quick-start-guide.md
- en/docs/learn/examples/jms-examples/guaranteed-delivery-with-failover.md
- en/docs/learn/examples/jms-examples/publish-subscribe-with-jms.md
- en/docs/learn/examples/message-transformation-examples/pox-to-json-conversion.md
- en/docs/learn/integration-use-case/file-processing-overview.md
- en/docs/learn/integration-use-case/protocol-switching-overview.md
- en/docs/learn/learn-overview.md
> Fix issues in links

- en/docs/reference/connectors/email-connector/email-connector-config.md
Related issue: https://github.com/wso2/micro-integrator/issues/3073 …
> Update email connector docs

- en/docs/googlefc84cfcfd6dd83b6.html
This PR is to remove the file with the Google site verification tracking code for the APIM doc space.
Google site verification tracking code for the MI doc space will be added by a separate PR.
> [Main] Remove the site verification code

- en/docs/googlefc84cfcfd6dd83b6.html
This PR is to remove the file with the Google site verification tracking code for the APIM doc space.
Google site verification tracking code for the MI doc space will be added by a separate PR.
> [4.2.0] Remove the site verification code

- en/theme/material/main.html
This PR is to add Google Search Console and Google Tag Manager tracking codes to the MI doc space.
- Mail: "Configuring Google Analytics & Search Console for MI Documentation Space"
- Mail: "Tracking codes"
> [Main] Add tracking codes

- en/theme/material/main.html
This PR is to add Google Search Console and Google Tag Manager tracking codes to the MI doc space.
- Mail: "Configuring Google Analytics & Search Console for MI Documentation Space"
- Mail: "Tracking codes"
> [4.2.0] Add tracking codes

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-config.md
> Add new S3 connector sdk version related jars

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-config.md
> [mi4.2.0] Add new S3 connector sdk version related jars

- en/docs/reference/connectors/smpp-connector/smpp-connector-configuration.md
Update SMPP docs with new SDK
https://github.com/wso2-extensions/esb-connector-smpp/pull/32
> Update SMPP docs with new SDK

- en/docs/install-and-setup/setup/brokers/configure-with-ibm-websphere-app-server.md
> [main] Fix invalid link

- en/docs/install-and-setup/setup/brokers/configure-with-ibm-websphere-app-server.md
> [4.2.0] Fix invalid link

- en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
> [4.2.0] Fix download link

- en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
> [main] Fix download link

- en/docs/reference/connectors/kafka-connector/kafka-connector-overview.md
- en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
- en/mkdocs.yml
$subject
Related PR https://github.com/wso2-extensions/esb-connector-kafka/pull/81
> [4.2.0] Update kafka connector documentation with 3.2.0 details

- en/docs/reference/connectors/kafka-connector/kafka-connector-overview.md
- en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
- en/mkdocs.yml
$subject
Related PR https://github.com/wso2-extensions/esb-connector-kafka/pull/81
> Update kafka connector documentation with 3.2.0 details

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject
Related issue https://github.com/wso2/api-manager/issues/2434
> Update VFS documentation with new parameters

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
Update s3 docs with getContentAsBase64 parameter
https://github.com/wso2-extensions/esb-connector-amazons3/pull/67
> Update s3 docs with getContentAsBase64 parameter

- en/docs/reference/synapse-properties/endpoint-properties.md
> Update synapse.timeout_handler_interval property in endpoint timeout doc

- en/docs/reference/connectors/file-connector/file-connector-config.md
- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
> Add note for username and password in VFS

- en/docs/reference/mediators/data-mapper-mediator.md
This PR is to update the directory path.
> [main] Update data-mapper-mediator.md

- en/docs/reference/mediators/data-mapper-mediator.md
This PR is to update the directory path.
> [4.3.0] Update data-mapper-mediator.md

- en/docs/reference/mediators/data-mapper-mediator.md
This PR is to update the directory path.
> [4.2.0] Update data-mapper-mediator.md

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
Related issue: https://github.com/wso2/micro-integrator/issues/3270 …
> Update AmazonS3 documentation

- en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-config.md
Related Issue: wso2/micro-integrator#3279 …
> Update Kafka Inbound Connector Doc

- en/docs/reference/connectors/iso8583-connector/iso8583-inbound-endpoint-config.md
Update ISO8583 inbound docs with 1993 version.
https://github.com/wso2-extensions/esb-inbound-iso8583/pull/20
> Update ISO8583 inbound docs with 1993 version

- en/docs/reference/connectors/file-connector/file-connector-config.md
Issue: https://github.com/wso2/micro-integrator/issues/3282
> Update file connector docs for fetchDirectoryContent operation

- en/docs/reference/connectors/file-connector/file-connector-config.md
Issue Reference: https://github.com/wso2/micro-integrator/issues/3282
> [main] Update file connector docs for fetchDirectoryContent operation

- en/docs/reference/connectors/file-connector/file-connector-config.md
Issue Reference: https://github.com/wso2/micro-integrator/issues/3282
> [4.3.0] Update file connector docs for fetchDirectoryContent operation

- en/docs/assets/versions.json
> Update versions.json with the URLs for staging doc

- en/mkdocs.yml
This PR is to add the API-led Integration page to the sidebar.
> [4.3.0] Update mkdocs.yml

- en/mkdocs.yml
This PR is to add the API-led Integration page to the sidebar.
> [4.2.0] Update mkdocs.yml

- en/mkdocs.yml
This PR is to add the API-led Integration page to the sidebar.
> [main] Update mkdocs.yml

- en/docs/install-and-setup/setup/message-builders-formatters/message-builders-and-formatters.md
This PR is to update the default Content-Type parameter for the requests.
Issue Reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/666
> [4.2.0] Update the default Content-Type parameter for the requests

- en/docs/install-and-setup/setup/message-builders-formatters/message-builders-and-formatters.md
This PR is to update the default Content-Type parameter for the requests.
Issue Reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/666
> [4.3.0] Update the default Content-Type parameter for the requests

- en/docs/install-and-setup/setup/message-builders-formatters/message-builders-and-formatters.md
This PR is to update the default Content-Type parameter for the requests.
Issue Reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/666
> [main] Update the default Content-Type parameter for the requests

- en/theme/material/main.html
This PR is to add a WIP banner to the 4.3.0 doc space.
> [4.3.0] Add WIP banner

- en/docs/reference/connectors/csv-module/csv-module-config.md
- en/mkdocs.yml
> [4.2.0] Add CSV Module doc

- en/docs/reference/connectors/csv-module/csv-module-config.md
- en/mkdocs.yml
> [4.3.0] Add CSV Module doc

- en/docs/reference/connectors/csv-module/csv-module-config.md
- en/mkdocs.yml
> [main] Add CSV Module doc

- en/docs/reference/connectors/redis-connector/2.7.x/redis-connector-reference.md
- en/mkdocs.yml
> [4.2.0] Add Redis Connector Reference doc

- en/docs/reference/connectors/redis-connector/2.7.x/redis-connector-reference.md
- en/mkdocs.yml
> [main] Add Redis Connector Reference doc

- en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
Update Kafka inbound endpoint setup guide
https://github.com/wso2/orbit/pull/1104
> Update Kafka inbound endpoint setup guide

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
> Add the transport.vfs.IsMounted parameter to VFS transport URL parameters.
> Update VFS transport URL parameters

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
> Reverse the change done to the VFS file uri example by [1].
[1] https://github.com/wso2/docs-mi/pull/182
> Reverse VFS file uri example

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject
https://github.com/wso2/docs-mi/pull/182
> [main] Update vfs-transport-parameters.md

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject
https://github.com/wso2/docs-mi/pull/182
> [4.3.0] Update vfs-transport-parameters.md

- en/docs/develop/mi-for-vscode/install-wso2-mi-for-vscode.md
> [4.2.0] Update installation path

- en/docs/includes/reference/connectors/exporting-artifacts.md
- en/docs/includes/reference/connectors/importing-connector-to-integration-studio.md
- en/docs/reference/connectors/kafka-connector/kafka-connector-avro-producer-example.md
- en/docs/reference/connectors/kafka-connector/kafka-connector-config.md
- en/docs/reference/connectors/kafka-connector/kafka-connector-producer-example.md
- en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
> [main] Fix formatting on the Kafka pages

- en/docs/includes/reference/connectors/exporting-artifacts.md
- en/docs/includes/reference/connectors/importing-connector-to-integration-studio.md
- en/docs/reference/connectors/kafka-connector/kafka-connector-avro-producer-example.md
- en/docs/reference/connectors/kafka-connector/kafka-connector-config.md
- en/docs/reference/connectors/kafka-connector/kafka-connector-producer-example.md
- en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
> [4.2.0] Update kafka docs

- en/docs/develop/mi-for-vscode/install-wso2-mi-for-vscode.md
> [4.2.0] Update vscode extension reference

- en/docs/develop/mi-for-vscode/install-wso2-mi-for-vscode.md
> [4.2.0] Update prerequisites

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/731
> [4.2.0] Update file connector doc with pool configs

- en/docs/reference/connectors/file-connector/file-connector-config.md
> Update file connector doc

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/731
> [main] Update file connector doc with pool configs

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/731
> [4.3.0] Update file connector doc with pool configs

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
https://github.com/wso2/docs-mi/pull/177 & https://github.com/wso2/docs-mi/pull/176
> [main] Update file-connector-config.md

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
https://github.com/wso2/docs-mi/pull/177 & https://github.com/wso2/docs-mi/pull/176
> [4.3.0] Update file-connector-config.md

- en/docs/develop/mi-for-vscode/install-wso2-mi-for-vscode.md
This PR is to remove the details on signing up for the AI services.
> Remove wso2mi account creation info

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
**Related PR**
https://github.com/wso2/docs-apim/pull/7307/
> [4.2.0] Update file-connector-config.md

- en/docs/get-started/development-kickstart.md
This PR is to update the image of the MI dashboard login page.
> [main] Update login page image

- en/docs/get-started/development-kickstart.md
This PR is to update the image of the MI dashboard login page.
> [4.2.0] Update login page image

- en/docs/get-started/development-kickstart.md
This PR is to update the image of the MI dashboard login page.
> [4.3.0] Update login page image

- en/docs/install-and-setup/setup/deployment/deploying-micro-integrator-with-helm.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/740
> [4.2.0] Update deploying-micro-integrator-with-helm.md

- en/docs/install-and-setup/setup/deployment/deploying-micro-integrator-with-helm.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/740
> [4.3.0] Update deploying-micro-integrator-with-helm.md

- en/docs/install-and-setup/setup/deployment/deploying-micro-integrator-with-helm.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/740
> [main] Update deploying-micro-integrator-with-helm.md

- en/docs/reference/connectors/ldap-connector/ldap-server-configuration.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/737
> [4.2.0] Update providerUrl description

- en/docs/reference/connectors/ldap-connector/ldap-server-configuration.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/737
> [4.3.0] Update providerUrl description

- en/docs/reference/connectors/ldap-connector/ldap-server-configuration.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/737
> [main] Update providerUrl description

- en/docs/reference/troubleshooting/error-handling-mi.md
This PR is to add the error code 601000 to the docs.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/777
> [4.2.0] Add error code 601000

- en/docs/reference/troubleshooting/error-handling-mi.md
This PR is to add the error code 601000 to the docs.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/777
> [4.3.0] Add error code 601000

- en/docs/reference/troubleshooting/error-handling-mi.md
This PR is to add the error code 601000 to the docs.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/777
> [main] Add error code 601000

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/741
> [main] Update file connector pool configs

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/741
> [4.3.0] Update file connector pool configs

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/741
> [4.2.0] Update file connector pool configs

- en/docs/install-and-setup/install/installation-prerequisites.md
This PR is to update the minimum recommended core count.
This will fix:
- https://github.com/wso2-enterprise/wso2-mi-internal/issues/112
- https://github.com/wso2-enterprise/wso2-mi-internal/issues/770
> [4.2.0] Update the minimum recommended core count

- en/docs/install-and-setup/install/installation-prerequisites.md
This PR is to update the minimum recommended core count.
This will fix:
- https://github.com/wso2-enterprise/wso2-mi-internal/issues/112
- https://github.com/wso2-enterprise/wso2-mi-internal/issues/770
> [main] Update the minimum recommended core count

- en/docs/mi-analytics/mi-elk-installation-guide.md
$subject
This will fix: https://github.com/wso2/docs-mi/issues/85
> [4.2.0] Update log4j2 path in ELK doc

- en/docs/mi-analytics/mi-elk-installation-guide.md
$subject
This will fix: https://github.com/wso2/docs-mi/issues/85
> [4.3.0] Update log4j2 path in ELK doc

- en/docs/mi-analytics/mi-elk-installation-guide.md
$subject
This will fix: https://github.com/wso2/docs-mi/issues/85
> [main] Update log4j2 path in ELK doc

- en/docs/reference/synapse-properties/endpoint-properties.md
$subject
https://github.com/wso2/docs-mi/pull/107
**Issue reference:**
https://github.com/wso2/docs-mi/issues/108
> [4.3.0] Update the `synapse.timeout_handler_interval` property

- en/docs/reference/synapse-properties/endpoint-properties.md
$subject
https://github.com/wso2/docs-mi/pull/107
**Issue reference:**
https://github.com/wso2/docs-mi/issues/108
> [main] Update the `synapse.timeout_handler_interval` property

- en/docs/reference/troubleshooting/error-handling-mi.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/831
> [4.2.0] Update error-handling-mi.md

- en/docs/reference/troubleshooting/error-handling-mi.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/831
> [main] Update error-handling-mi.md

- en/docs/reference/troubleshooting/error-handling-mi.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/831
> [4.3.0] Update error-handling-mi.md

- en/docs/reference/config-catalog-mi-dashboard.md
> Update integration control plane docs

- en/docs/reference/config-catalog-mi-dashboard.md
Add docs for https://github.com/wso2/product-mi-tooling/pull/368
Fix wso2/api-manager#1999
> Link to the PR for changes to the …
> Update configurable parameters

- en/docs/develop/customizations/creating-synapse-handlers.md
$subject
**Issue reference:** https://github.com/wso2/docs-mi/issues/258
> [4.2.0] Update toml config in Synapse Handlers

- en/requirements.txt
This PR is to add the requirements.txt file to the staging-versions branch.
> Add the requirements.txt file

- en/docs/develop/mi-for-vscode/install-wso2-mi-for-vscode.md
This PR is to fix a broken link.
Issue reference: https://github.com/wso2/docs-mi/issues/291.
> [4.3.0] Update install-wso2-mi-for-vscode.md

- en/docs/develop/mi-for-vscode/install-wso2-mi-for-vscode.md
This PR is to fix a broken link.
Issue reference: https://github.com/wso2/docs-mi/issues/291.
> [4.2.0] Update install-wso2-mi-for-vscode.md

- en/docs/reference/mediators/data-mapper-mediator.md
> Add nashorn es6 related system property to datamapper docs

- en/docs/learn/examples/file-processing/accessing-windows-share-using-vfs-transport.md
This PR is to update the URI format on the `Access a Windows Share Using VFS` page.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/449
> [main] Update the URI format

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
> [4.3.0] Update s3 docs with getContentAsBase64 parameter

- en/docs/assets/css/mitheme.css
- en/docs/assets/js/mitheme.js
- en/theme/material/partials/header.html
This PR is to add the custom dropdown component to the staging-4.3.0 branch.
> [staging-4.3.0] Add custom dropdown component

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/698
> [4.2.0] Update the file connector doc with retry configs

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/698
> [4.3.0] Update the file connector doc with retry configs

- en/docs/develop/customizations/creating-synapse-handlers.md
$subject
**Issue reference:** https://github.com/wso2/docs-mi/issues/258
> [4.3.0] Update toml config in Synapse Handlers

- en/docs/reference/connectors/amazonlambda-connector/amazonlambda-connector-config.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/721
> [4.3.0] Update amazonlambda-connector-config.md

- en/docs/reference/connectors/amazonlambda-connector/amazonlambda-connector-config.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/721
> [4.2.0] Update amazonlambda-connector-config.md

- en/theme/material/partials/copyright.html
This PR is to update the copyright notice for MI 4.3.0 documentation. 
Need to follow the company standard for copyright notice based on the initial year the documentation was created to the current year.
Mail: "Discrepancies in the documentation copyrights statement"
**Issue Reference:**
https://github.com/wso2/docs-mi/issues/304
> [4.3.0] Update copyright.html

- en/docs/includes/build-and-run-artifacts.md
- en/docs/includes/build-and-run.md
- en/docs/includes/create-new-project.md
- en/docs/includes/setting-up-workspace-for-mi-for-vscode.md
This PR is to add the following files to the `includes` directory for the common content:
- build-and-run.md
- build-and-run-artifacts.md
- create-new-project.md
- setting-up-workspace-for-mi-for-vscode.md
> [4.3.0] Add includes

- en/docs/includes/build-and-run.md
> Update file path

- en/docs/includes/build-and-run.md
> Remove line

- en/mkdocs.yml
$subject
**Issue reference:** https://github.com/wso2/docs-mi/issues/322
> [4.3.0] Fix redirection issue

- en/mkdocs.yml
$subject
**Issue reference:** https://github.com/wso2/docs-mi/issues/322
> [4.2.0] Fix redirection issue

- README.md
- en/mkdocs.yml
Add missing step for running the project locally
> Add missing steps for running the project locally

- en/docs/learn/examples/endpoint-examples/using-address-endpoints.md
- en/docs/learn/examples/endpoint-examples/using-failover-endpoints.md
> Fix address and failover endpoint docs
> Fix address and failover endpoint docs

- en/docs/learn/examples/data-integration/csv-data-service.md
> Update `Exposing an CSV Datasource` page

- en/docs/learn/examples/data-integration/carbon-data-service.md
- en/docs/learn/examples/data-integration/mongo-data-service.md
- en/docs/learn/examples/data-integration/rdbms-data-service.md
This PR updates the following docs
- Exposing a Mongo Datasource
- Exposing a Carbon Datasource as a Data Service
> Doc update for VScode extension

- en/docs/develop/mi-for-vscode/mi-for-vscode-overview.md
> [4.3.0] Update mi for vs code overview page

- en/docs/develop/mi-for-vscode/troubleshooting-mi-for-vscode.md
- en/mkdocs.yml
This PR is to add the troubleshooting guide page to the doc space. The content will be added later.
> [4.3.0] Add troubleshooting guide page

- en/docs/learn/examples/data-integration/swagger-data-services.md
> Update `Publishing a Custom Swagger Document` page

- en/docs/reference/troubleshooting/utilizing-runtime-diagnostic-tool.md
- en/mkdocs.yml
$subject
Related to https://github.com/wso2/micro-integrator/issues/2985
> Add docs for runtime diagnostic tool

- en/mkdocs.yml
This PR is to remove the Package Artifacts page from the page structure and set a redirection for the removed URL.
> [4.3.0] Package artifacts page

- en/mkdocs.yml
> Add sample page link

- en/docs/learn/examples/routing-examples/routing-based-on-headers.md
> Update the doc of Routing based on message headers 

- en/docs/learn/examples/routing-examples/routing-based-on-payloads.md
> Update route based on message payload doc

- en/docs/learn/examples/routing-examples/splitting-aggregating-messages.md
> Update split messages and aggregating responses doc

- en/docs/learn/examples/protocol-switching/switching-from-tcp-to-https.md
https://mi.docs.wso2.com/en/4.3.0/learn/examples/protocol-switching/switching-from-tcp-to-https/
> Update "Switching from TCP to HTTP/S" page

- en/docs/learn/examples/file-processing/vfs-transport-examples.md
> Update the page on "VFS Transport"

- en/docs/learn/examples/rabbitmq-examples/point-to-point-rabbitmq.md
> Update point to point RabbitMQ page

- en/docs/learn/examples/rabbitmq-examples/pub-sub-rabbitmq.md
> Update the publish subscribe rabbitmq page

- en/docs/learn/examples/rabbitmq-examples/store-forward-rabbitmq.md
> Update store and forward rabbitmq page

- en/docs/learn/examples/rabbitmq-examples/retry-delay-failed-msgs-rabbitmq.md
> Update Retry failed messages with delay page

- en/docs/learn/examples/rabbitmq-examples/requeue-msgs-with-errors-rabbitmq.md
> Update Requeue messages with RabbitMQ page

- en/docs/learn/examples/message-transformation-examples/pox-to-json-conversion.md
> Update converting POX Messages to JSON doc

- en/docs/develop/opening-projects.md
- en/mkdocs.yml
> [4.3.0] Update opening a project page

- en/docs/learn/samples/jms-integration.md
- en/docs/learn/samples/message-filtering.md
- en/docs/learn/samples/protocol-switching.md
- en/docs/learn/samples/proxying-rest-service.md
- en/docs/learn/samples/proxying-soap-service.md
- en/docs/learn/samples/scatter-gather-integration-pattern.md
- en/mkdocs.yml
Add doc pages for samples
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
> Add doc pages for samples

- en/docs/learn/samples/api-testing.md
This PR will introduce documentations on how to deploy and work with MI sample projects via the MI VS Code Extension.
> MI sample projects documentation for VS Code extension

- en/docs/get-started/key-concepts.md
- en/mkdocs.yml
> Remove service catalog related content

- en/docs/install-and-setup/install-and-setup-overview.md
- en/docs/install-and-setup/install/installing-mi-dashboard.md
- en/docs/install-and-setup/install/running-the-mi-dashboard-as-windows-service.md
- en/docs/install-and-setup/install/running-the-mi-dashboard.md
- en/mkdocs.yml
> Migrate dashboard install/run docs with ICP

- en/docs/get-started/quick-start-guide.md
> [WIP] update get started page

- en/docs/learn/examples/protocol-switching/switching-from-http-to-fix.md
https://mi.docs.wso2.com/en/4.3.0/learn/examples/protocol-switching/switching-from-http-to-fix/
> Update "Switching from HTTP to FIX" Doc

- en/docs/learn/examples/rest-api-examples/setting-query-params-outgoing-messages.md
> Remove out sequence from setting query params on outgoing messages example

- en/docs/learn/examples/rest-api-examples/enabling-rest-to-soap.md
> Remove outSequence from enabling rest to soap example

- en/docs/assets/css/mitheme.css
- en/docs/assets/js/mitheme.js
- en/theme/material/partials/header.html
This PR is to add the custom dropdown component to the staging-4.2.0 branch.
> [staging-4.2.0] Add custom dropdown component

- en/mkdocs.yml
> [staging-4.2.0] Update site_name

- en/mkdocs.yml
> [staging-4.3.0] Update site_name

- en/docs/learn/examples/rest-api-examples/setting-https-status-codes.md
> Update the "Handling HTTP Status Codes" page

- en/docs/learn/examples/rest-api-examples/handling-non-matching-resources.md
> Update the "Handling Non-Matching Resources" page

- en/docs/learn/examples/rest-api-examples/transforming-content-type.md
> Update the "Transforming Content Types" Page

- en/docs/learn/examples/inbound-endpoint-examples/inbound-endpoint-jms-protocol.md
> Update the JMS inbound endpoint page

- en/docs/learn/examples/inbound-endpoint-examples/file-inbound-endpoint.md
> Update "Using the File Inbound Endpoint" page

- en/docs/learn/examples/inbound-endpoint-examples/inbound-endpoint-http-protocol.md
> Update http inbound endpoint page

- en/docs/learn/examples/inbound-endpoint-examples/inbound-endpoint-rabbitmq-protocol.md
> Update the Rabbitmq inbound endpoint page

- en/docs/learn/examples/inbound-endpoint-examples/inbound-endpoint-kafka.md
> Update Using the Kafka Inbound Endpoint page

- en/docs/learn/examples/inbound-endpoint-examples/inbound-endpoint-with-registry.md
> Update Using inbound with registry page

- en/docs/learn/examples/rest-api-examples/publishing-a-swagger-api.md
> Update the page on "Publishing a Custom Swagger Document"

- en/docs/learn/examples/inbound-endpoint-examples/inbound-endpoint-hl7-protocol-auto-ack.md
> Update page on, "Using the HL7 Inbound Endpoint (with Auto Ack)"

- en/docs/learn/examples/message-store-processor-examples/intro-message-stores-processors.md
> Update doc for Message Stores

- en/docs/learn/examples/proxy-service-examples/publishing-a-custom-wsdl.md
> Update Publishing a Custom WSDL page

- en/docs/learn/examples/proxy-service-examples/introduction-to-proxy-services.md
> Update Use a Simple proxy service page

- en/docs/learn/examples/scheduled-tasks/injecting-messages-to-rest-endpoint.md
> Update page on "Injecting Messages to a RESTful Endpoint"

- en/docs/learn/examples/scheduled-tasks/task-scheduling-simple-trigger.md
> Update the page on, "Task Scheduling using a Simple Trigger"

- en/docs/learn/examples/message-store-processor-examples/using-jdbc-message-store.md
> Update doc for jdbc data store

- en/docs/learn/examples/message-store-processor-examples/using-jms-message-stores.md
Update the doc for jms message store
> Update the doc for jms message store

- en/docs/learn/examples/message-store-processor-examples/using-rabbitmq-message-stores.md
> Update the "Using RabbitMQ message store" page

- en/docs/learn/examples/message-store-processor-examples/using-message-sampling-processor.md
Update the doc for message sampling processor
> Update the doc for message sampling processor

- en/docs/learn/examples/message-store-processor-examples/using-message-forwarding-processor.md
Update doc for message forwarding processor
> Update doc for message forwarding processor

- en/docs/learn/examples/message-store-processor-examples/securing-message-processor.md
Update doc for secure message processor
> Update doc for secure message processor

- en/docs/learn/examples/endpoint-examples/using-websocket-endpoints.md
https://mi.docs.wso2.com/en/latest/learn/examples/endpoint-examples/using-websocket-endpoints/
> Update "Using a WebSocket Endpoint" Doc

- en/docs/learn/examples/endpoint-examples/using-loadbalancing-endpoints.md
> Update "Using load balancing endpoint" page

- en/docs/learn/examples/sequence-examples/using-multiple-sequences.md
> Update the page on "Breaking Complex Flows into Multiple Sequences"

- en/docs/learn/examples/proxy-service-examples/exposing-proxy-via-inbound.md
> Update Exposing a Proxy Service via Inbound Endpoint page

- en/docs/learn/examples/transport-examples/tcp-transport-examples.md
https://mi.docs.wso2.com/en/4.3.0/learn/examples/transport-examples/tcp-transport-examples/
> Update Using the TCP Transport doc

- en/docs/learn/examples/hl7-examples/hl7-proxy-service.md
> Update the page on "Mediating HL7 Messages"

- en/docs/learn/examples/hl7-examples/file-transfer-using-hl7.md
> Update page on, "Using HL7 Messages with File Systems"

- en/docs/learn/examples/inbound-endpoint-examples/inbound-endpoint-mqtt-protocol.md
> Update "Using the MQTT Inbound Endpoint" page

- en/docs/learn/examples/hl7-examples/acknowledge-hl7-messages.md
> Update the page on "Acknowledging HL7 Messages"

- en/docs/learn/examples/sequence-examples/using-fault-sequences.md
> Update the page on, "Using Fault Sequences"

- en/docs/learn/learn-overview.md
- en/mkdocs.yml
$subject
Temporarily remove the pages from the page tree and set redirections.
---
Related issue: https://github.com/wso2/docs-mi/issues/515
> [4.3.0] Remove service catalog related pages

- en/docs/learn/examples/sequence-examples/custom-sequences-with-proxy-services.md
> Update page on "Reusing sequences"

- en/docs/reference/connectors/iso8583-connector/iso8583-connector-example.md
> Update the page on "ISO8583 Connector Example"

- en/docs/reference/connectors/google-firebase-connector/google-firebase-connector-example.md
> Update the page on "Google Firebase Connector Example"

- en/docs/reference/connectors/fhir-connector/fhir-connector-example.md
> Update the page on "FHIR Connector Example"

- en/docs/get-started/about-this-release.md
> Add release features doc

- en/docs/learn/examples/inbound-endpoint-examples/inbound-endpoint-https-protocol.md
> Update the HTTPS inbound endpoint page

- en/docs/get-started/quick-start-guide.md
> Update the quick start guide code and output

- en/docs/get-started/development-kickstart.md
> Add en/docs/get-started/development-kickstart.md

- en/docs/reference/mediators/log-mediator.md
https://mi.docs.wso2.com/en/4.3.0/reference/mediators/log-mediator/
> Update log mediator doc

- en/docs/reference/mediators/aggregate-mediator.md
> Update Aggregate mediator catalog

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> [4.3.0] Update the product compatibility page

- en/docs/learn/examples/protocol-switching/switching-from-fix-to-http.md
> Update "Switch from FIX to HTTP" Doc

- en/theme/material/main.html
This PR is to remove the WIP banner from the 4.3.0 doc space.
> [4.3.0] Remove WIP banner

- en/docs/learn/learn-overview.md
- en/mkdocs.yml
> [4.3.0] Update tutorials section

- en/mkdocs.yml
> Update page structure

- en/docs/install-and-setup/install/running-the-mi-dashboard.md
> Fix formatting

- en/docs/learn/examples/file-processing/mailto-transport-examples.md
> Update the page on mail to transport example

- en/docs/learn/examples/protocol-switching/switching-from-jms-to-http.md
> Update the page on "Switching from JMS to HTTP(S)"

- en/docs/index.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/179.
> [4.2.0] Fix search results pane styling issue

- en/docs/index.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/179.
Updated search results pane will look like this: 
https://github.com/user-attachments/assets/18a6ca58-a49b-4888-9c85-3b8736ba2338
> [4.3.0] Fix search results pane styling issue

- en/docs/learn/examples/inbound-endpoint-examples/inbound-endpoint-secured-websocket.md
[https://mi.docs.wso2.com/en/4.3.0/learn/examples/inbound-endpoint-examples/inbound-endpoint-secured-websocket/ ](https://mi.docs.wso2.com/en/4.3.0/learn/examples/inbound-endpoint-examples/inbound-endpoint-secured-websocket/ )
> Update using Secure WebSocket Inbound Endpoint doc

- en/docs/learn/examples/proxy-service-examples/securing-proxy-services.md
> This PR includes updates to the below mentioned page. https://mi.docs.wso2.com/en/4.3.0/learn/examples/proxy-service-examples/securing-proxy-services/
> Update Securing a Proxy Service page

- en/docs/reference/mediators/throttle-mediator.md
> Update throttle mediator catalog

- en/docs/get-started/development-kickstart.md
- en/docs/get-started/quick-start-guide.md
> Fix language issues

- en/docs/reference/mediators/switch-mediator.md
https://mi.docs.wso2.com/en/4.3.0/reference/mediators/switch-mediator/
> Update Switch Mediator Doc

- en/docs/reference/mediators/store-mediator.md
> Update store mediator catalog

- en/docs/reference/mediators/sequence-mediator.md
https://mi.docs.wso2.com/en/4.3.0/reference/mediators/sequence-mediator/
> Update sequence mediator doc

- en/docs/reference/mediators/send-mediator.md
> Update Send mediator catalog

- en/docs/reference/mediators/script-mediator.md
> Update script mediator catalog

- en/docs/reference/mediators/respond-mediator.md
https://mi.docs.wso2.com/en/4.3.0/reference/mediators/respond-mediator/
> Update respond mediator doc

- en/docs/reference/mediators/cache-mediator.md
> Update cache mediator catalog

- en/docs/reference/mediators/payloadfactory-mediator.md
> Update the page on "Payload mediator"

- en/docs/develop/creating-artifacts/using-docker-secrets.md
> $title
https://mi.docs.wso2.com/en/4.3.0/develop/creating-artifacts/using-docker-secrets/#enabling-secrets-in-the-environment
> …
> Update the using the 'Using Docker Secrets in Synapse Configurations' page

- en/docs/reference/mediators/db-report-mediator.md
> Update DB Report mediator catalog

- en/docs/reference/mediators/enrich-mediator.md
https://mi.docs.wso2.com/en/latest/reference/mediators/enrich-mediator/
> Update "Enrich Mediator" Doc

- en/docs/reference/mediators/loopback-mediator.md
> Update the page on loopback mediator

- en/docs/learn/examples/jms-examples/producing-jms.md
> Update the producing JMS messages page

- en/docs/learn/examples/rest-api-examples/configuring-non-http-endpoints.md
> Update Exposing Non-HTTP Services as RESTful APIs page

- en/docs/reference/mediators/drop-mediator.md
https://mi.docs.wso2.com/en/4.3.0/reference/mediators/drop-mediator/
> Update drop mediator doc

- en/docs/get-started/development-kickstart.md
- en/docs/get-started/quick-start-guide.md
> Update ICP download link in QSG and Kickstart

- en/docs/develop/customizations/creating-new-connector.md
> Fix formatting issues in the creating new connector page

- en/docs/reference/mediators/iterate-mediator.md
> Update iterate mediator catalog

- en/docs/reference/mediators/header-mediator.md
> Update header mediator catalog

- en/docs/develop/generate-docker-image.md
This PR will add a note to the docker image build documentation with regard to setting up the DOCKER_HOST environmental variable.
> Update docker image build documentation

- en/docs/reference/mediators/call-mediator.md
> Refactor call mediator examples

- en/docs/learn/examples/rest-api-examples/securing-rest-apis.md
> Update the page on, "Securing REST APIs"

- en/docs/learn/examples/template-examples/using-sequence-templates.md
Update the doc of sequence template
> Update the doc for sequence template

- en/docs/learn/examples/template-examples/using-endpoint-templates.md
Update the doc for endpoint template
> Update the doc for endpoint template

- en/docs/learn/examples/endpoint-examples/using-wsdl-endpoints.md
> Update "Using WSDL endpoint" page

- en/docs/learn/examples/integrating-mi-with-si.md
> Update the page on integrating with SI

- en/docs/learn/examples/jms-examples/quad-channel-jms-to-jms.md
> Update the quad channel jms page

- en/docs/learn/examples/jms-examples/shared-topic-subscription.md
> Update shared topic subscription page

- en/docs/learn/examples/jms-examples/detecting-repeatedly-redelivered-messages.md
> Update detecting repeated delivery jms page

- en/docs/develop/advanced-development/applying-security-to-an-api.md
> Update the applying security to a REST API page

- en/docs/reference/mediators/callout-mediator.md
> Update callout mediator catalog

- en/docs/reference/mediators/class-mediator.md
> Update Class mediator catalog

- en/docs/reference/mediators/fault-mediator.md
https://mi.docs.wso2.com/en/latest/reference/mediators/fault-mediator/
> Update "Fault Mediator" Doc

- en/docs/learn/integration-tutorials/using-inbound-endpoints.md
> Update Using inbound endpoints tutorial page

- en/docs/reference/synapse-properties/proxy-service-properties.md
https://mi.docs.wso2.com/en/latest/reference/synapse-properties/proxy-service-properties/
> Update "Proxy Service Properties" Doc

- en/docs/reference/mediators/property-mediator.md
> Update the page on property mediator

- en/docs/learn/examples/message-transformation-examples/json-to-soap-conversion.md
> Update "Converting JSON to SOAP" Doc

- en/docs/learn/examples/file-processing/accessing-windows-share-using-vfs-transport.md
> Update Windows share VFS page

- en/docs/learn/examples/rabbitmq-examples/request-response-rabbitmq.md
> Update request response rabbitmq page

- en/docs/learn/examples/jms-examples/dual-channel-http-to-jms.md
> Update dual channel http to JMS page

- en/docs/learn/examples/jms-examples/guaranteed-delivery-with-failover.md
> Update guaranteed delivery with JMS page

- en/docs/learn/examples/jms-examples/publish-subscribe-with-jms.md
> Update publish subscribe with jms page

- en/docs/learn/examples/jms-examples/specifying-a-delivery-delay-on-messages.md
> Update delivery delay with jms page

- en/mkdocs.yml
> Add redirect for "Switch from FIX to AMQP" Doc

- en/docs/reference/mediators/xslt-mediator.md
> Update XSLT mediator catalog

- en/docs/learn/examples/jms-examples/guaranteed-delivery-with-failover.md
> $Subject
Fixes https://github.com/wso2/docs-mi/issues/676 …
> Fix code sample issues in "Guaranteed delivery with JMS" page

- en/docs/get-started/introduction.md
> Fix introduction page issues

- en/docs/learn/examples/protocol-switching/switching-between-http-and-msmq.md
> Update switching between http and MSMQ page

- en/docs/reference/connectors/connectors-overview.md
> Update Connectors Overview page

- en/docs/learn/examples/jms-examples/consume-produce-jms.md
> Update consume produce jms messages page

- en/docs/learn/examples/rabbitmq-examples/move-msgs-to-dlq-rabbitmq.md
> Update publishing messages to dead letter exchange page

- en/docs/reference/mediators/xslt-mediator.md
> $title 
Based on the discussion in https://github.com/wso2/mi-vscode/issues/321#issuecomment-2268163280 the XSLT mediator catalog page needs to be updated as proposed in this PR.
> Update some outdated information in XSLT Mediator catalog

- en/docs/develop/advanced-development/changing-the-endpoint-of-deployed-service.md
- en/docs/develop/advanced-development/using-swagger-for-apis.md
- en/docs/install-and-setup/setup/security/encrypting-plain-text.md
- en/docs/learn/examples/endpoint-examples/endpoint-error-handling.md
- en/docs/learn/examples/endpoint-examples/mtom-swa-with-endpoints.md
- en/docs/learn/examples/endpoint-examples/using-static-recepient-list-endpoints.md
- en/mkdocs.yml
This PR updates several pages in the MI 4.3.0 documentation to align them with the latest MI 4.3.0 release. Additionally, it hides pages related to features that are yet to be implemented in the MI VS Code extension.
> Updating docs for MI 4.3.0 release

- en/docs/learn/enterprise-integration-patterns/messaging-systems/message-channels.md
> Add doc link in message channel eip

- en/docs/learn/examples/message-store-processor-examples/loadbalancing-with-message-processor.md
[Update doc for load balancing with message processor](https://github.com/wso2/docs-mi/commit/9af5434147093fa08164140127ccf10374be52ab)
> Update doc for load balancing with message processor

- en/docs/learn/enterprise-integration-patterns/messaging-systems/message-channels.md
> Fix issues in message channel EIP

- en/docs/learn/enterprise-integration-patterns/messaging-systems/pipes-and-filters.md
> Update EIP pipes and filters page

- en/docs/learn/enterprise-integration-patterns/messaging-channels/datatype-channel.md
> Update EIP datatype channel page

- en/docs/learn/enterprise-integration-patterns/messaging-channels/guaranteed-delivery.md
> Update EIP guaranteed delivery page

- en/docs/learn/enterprise-integration-patterns/message-construction/overview.md
- en/docs/learn/enterprise-integration-patterns/message-routing/overview.md
- en/docs/learn/enterprise-integration-patterns/message-transformation/overview.md
- en/docs/learn/enterprise-integration-patterns/messaging-channels/overview.md
- en/docs/learn/enterprise-integration-patterns/messaging-endpoints/overview.md
- en/docs/learn/enterprise-integration-patterns/messaging-systems/overview.md
- en/docs/learn/enterprise-integration-patterns/system-management/overview.md
> Update EIP overview pages

- en/docs/learn/enterprise-integration-patterns/message-construction/request-reply.md
- en/docs/learn/enterprise-integration-patterns/message-routing/composed-message-processor.md
- en/docs/learn/enterprise-integration-patterns/message-routing/routing-slip.md
- en/docs/learn/enterprise-integration-patterns/message-transformation/claim-check.md
- en/docs/learn/enterprise-integration-patterns/messaging-channels/messaging-bridge.md
- en/docs/learn/enterprise-integration-patterns/messaging-channels/point-to-point-channel.md
- en/docs/learn/enterprise-integration-patterns/messaging-systems/message-channels.md
- en/docs/learn/enterprise-integration-patterns/messaging-systems/message-endpoint.md
- en/docs/learn/enterprise-integration-patterns/messaging-systems/message-router.md
> Fix links of build and run

- en/docs/learn/enterprise-integration-patterns/message-construction/format-indicator.md
> Update format indicator EIP

- en/docs/learn/enterprise-integration-patterns/message-transformation/canonical-data-model.md
> Update "Canonical Data Model" Doc

- en/docs/learn/examples/integrating-mi-with-si.md
- en/docs/reference/connectors/amazonsqs-connector/1.x/amazonsqs-connector-1.x-example.md
- en/docs/reference/connectors/connector-usage.md
- en/docs/reference/connectors/email-connector/email-connector-example.md
- en/docs/reference/connectors/google-pubsub-connector/googlepubsub-connector-example.md
- en/docs/reference/connectors/iso8583-connector/iso8583-connector-overview.md
- en/docs/reference/mediators/call-mediator.md
- en/docs/reference/mediators/validate-mediator.md
> Fix Broken links

- en/docs/learn/enterprise-integration-patterns/message-construction/message-sequence.md
> Update the message sequence EIP

- en/docs/learn/enterprise-integration-patterns/message-construction/correlation-identifier.md
> Update EIP on Correlation Identifier

- en/docs/learn/enterprise-integration-patterns/message-routing/composed-message-processor.md
- en/docs/learn/enterprise-integration-patterns/message-routing/routing-slip.md
- en/docs/learn/enterprise-integration-patterns/message-transformation/claim-check.md
- en/docs/learn/enterprise-integration-patterns/messaging-channels/messaging-bridge.md
> Remove figure names in the table of EIP pattern

- en/docs/learn/enterprise-integration-patterns/messaging-endpoints/polling-consumer.md
> Update "Polling Consumer" Doc

- en/docs/reference/connectors/why-connectors.md
- en/mkdocs.yml
Connector development guide is duplicate. Removing it. …
> Remove duplicate doc

- en/docs/learn/learn-overview.md
- en/mkdocs.yml
> Update redirect paths needed for page `switching-from-fix-to-amqp` 

- en/docs/learn/enterprise-integration-patterns/message-routing/process-manager.md
> Update EIP process manager page

- en/docs/learn/enterprise-integration-patterns/messaging-endpoints/messaging-mapper.md
> Update "Messaging Mapper" Doc

- en/docs/get-started/key-concepts.md
> Fix key concepts page

- en/docs/get-started/development-kickstart.md
> Fix develop your first integration content

- en/docs/reference/mediators/enrich-mediator.md
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves #807
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …
> fix typo issue #807

- en/docs/learn/enterprise-integration-patterns/eip-overview.md
- en/docs/learn/enterprise-integration-patterns/message-construction/overview.md
- en/docs/learn/enterprise-integration-patterns/message-transformation/overview.md
- en/docs/learn/enterprise-integration-patterns/messaging-channels/overview.md
- en/docs/learn/enterprise-integration-patterns/messaging-endpoints/overview.md
- en/mkdocs.yml
This PR is to,
- add EIP pages to the site navigation (left sidebar).
- temporarily remove the WIP pages from the overview pages.
> [4.3.0] Update EIP content

- en/docs/index.md
$subject
Issue reference: https://github.com/wso2/docs-mi/issues/818
> Update reference to EIP content

- en/docs/learn/enterprise-integration-patterns/eip-overview.md
- en/docs/learn/enterprise-integration-patterns/messaging-endpoints/overview.md
- en/mkdocs.yml
This PR is to add the messaging gateway page to the site navigation since the content is updated via https://github.com/wso2/docs-mi/pull/755/.
> Add messaging gateway to site navigation

- en/docs/get-started/quick-start-guide.md
Fix based on https://github.com/wso2/docs-mi/pull/797#discussion_r1722054942
> Fix sign in wording

- en/docs/learn/enterprise-integration-patterns/eip-overview.md
- en/docs/learn/enterprise-integration-patterns/message-construction/overview.md
- en/docs/learn/enterprise-integration-patterns/messaging-channels/overview.md
This PR is to add the following pages to the site navigation since the content is updated via https://github.com/wso2/docs-mi/pull/772/files and https://github.com/wso2/docs-mi/pull/707/files.
- Event Message
- Message Bus
> [4.3.0] Add updated EIP pages to site navigation

- en/docs/install-and-setup/install/installing-integration-control-plane.md
- en/docs/install-and-setup/install/running-the-integration-control-plane.md
- en/docs/observe-and-manage/working-with-integration-control-plane.md
This PR is to update the content related to ICP.
> [4.3.0] Update ICP pages

- en/docs/learn/enterprise-integration-patterns/messaging-channels/channel-adapter.md
> Update EIP channel adapter page

- en/docs/reference/mediators/aggregate-mediator.md
- en/docs/reference/mediators/clone-mediator.md
- en/docs/reference/mediators/iterate-mediator.md
This PR is to update the EIP references.
Issue reference: https://github.com/wso2/docs-mi/issues/764
> Update EIP references

- en/mkdocs.yml
This PR is to remove the following pages from the site nav and add redirections for them. 
- Connectors > Microsoft Azure Storage Example 1.x
- Create Artifacts > Create an Inbound Endpoint
Note: Once the pages are updated remove the redirections.
> Remove the pages to be updated

- en/docs/learn/learn-overview.md
> Update learn overview page

- en/docs/learn/samples/samples-overview.md
> Update samples overview page

- en/docs/learn/integration-use-case/file-processing-overview.md
> Update file processing doc

- en/mkdocs.yml
> Fix redirect page for installing mi dashboard page

- en/docs/observe-and-manage/managing-integrations-with-micli.md
> Update CLI version in example

- en/docs/learn/examples/routing-examples/routing-based-on-headers.md
> Update "Routing Based on Message Headers" Doc

- en/docs/learn/examples/routing-examples/routing-based-on-payloads.md
> Update "Routing Based on Message Payloads" Doc

- en/docs/learn/enterprise-integration-patterns/message-construction/message-expiration.md
- en/docs/learn/enterprise-integration-patterns/message-routing/composed-message-processor.md
- en/docs/learn/enterprise-integration-patterns/message-routing/routing-slip.md
- en/docs/learn/enterprise-integration-patterns/message-routing/splitter.md
- en/docs/learn/enterprise-integration-patterns/message-transformation/claim-check.md
- en/docs/learn/enterprise-integration-patterns/message-transformation/normalizer.md
- en/docs/learn/enterprise-integration-patterns/messaging-channels/messaging-bridge.md
- en/docs/learn/enterprise-integration-patterns/messaging-systems/message-channels.md
- en/docs/learn/enterprise-integration-patterns/messaging-systems/message-router.md
> Replace curl commands in EIP docs

- en/docs/reference/config-catalog-integration-control-plane.md
- en/mkdocs.yml
> Add redirect to renamed page

- en/docs/learn/examples/routing-examples/splitting-aggregating-messages.md
> Update "Splitting Messages and Aggregating Responses" Doc

- en/docs/reference/mediators/about-mediators.md
This PR is to update the list of mediators. I have updated the mediator categorization according to the mediator palette in the MI for VS Code extension.
This will fix https://github.com/wso2/docs-mi/issues/837.
> [4.3.0] Update about-mediators.md

- en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-config.md
$subject
Related:
https://github.com/wso2/docs-mi/issues/123
> [4.3.0] Update Kafka Inbound Connector Doc

- en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-config.md
$subject
Related:
https://github.com/wso2/docs-mi/issues/123
> [4.2.0] Update Kafka Inbound Connector Doc

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/122.
> [4.2.0] Update amazons3-connector-reference.md

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/122.
> [4.3.0] Update amazons3-connector-reference.md

- en/docs/install-and-setup/setup/brokers/configure-with-activemq.md
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves #832 
Improve documentation for the new AMQ version and making the breaking changes visible of AMQ 5.18.X and mentioning JMS 2.0 functionality and the effective it has on the micro integrator libs needed
> Brief description of the new …
> update documentation  with JMS 2.0

- en/docs/learn/examples/protocol-switching/switching-from-tcp-to-https.md
> Update "Switching from TCP to HTTP/S" Doc

- en/docs/learn/examples/transport-examples/tcp-transport-examples.md
> Update "Using the TCP Transport" Doc

- en/docs/learn/examples/file-processing/accessing-windows-share-using-vfs-transport.md
This PR is to update the URI format on the `Access a Windows Share Using VFS` page.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/449
> [4.3.0] Update the URI format 

- en/docs/reference/connectors/file-connector/file-connector-config.md
- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/116.
> [4.3.0] Add note for username and password

- en/docs/includes/create-new-project.md
This PR is to update the image URL.
> Update image URL

- en/docs/reference/connectors/smpp-connector/smpp-connector-configuration.md
> Update the jsmpp jar location

- en/docs/reference/connectors/amazonsqs-connector/amazon-inbound-endpoint-1.0.x/amazonsqs-inbound-endpoint-reference-configuration.md
- en/docs/reference/connectors/amazonsqs-connector/amazonsqs-inbound-endpoint-reference-configuration.md
- en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-config.md
This PR resolves the following issues.
- https://github.com/wso2/docs-mi/issues/637
- https://github.com/wso2/docs-mi/issues/625
> Fix SQS and Kafka inbound reference documentations

- en/docs/observe-and-manage/setting-up-cloud-native-observability-in-kubernetes.md
- en/docs/observe-and-manage/setting-up-cloud-native-observability-on-a-vm.md
Update Tracing configs
Fixes https://github.com/wso2/docs-mi/issues/840
> Update Tracing configs

- en/docs/develop/intro-integration-development.md
- en/mkdocs.yml
Disable this page until this is supported in VS Code. 
https://github.com/wso2/mi-vscode/issues/307
> Disable the data service custom validator page

- en/docs/reference/connectors/email-connector/email-connector-config.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/65.
> [4.2.0] Update email-connector-config.md

- en/docs/reference/connectors/email-connector/email-connector-config.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/65.
> [4.3.0] Update email-connector-config.md

- en/docs/get-started/development-kickstart.md
This is to use only one option to test the scenario.
Fix https://github.com/wso2/docs-mi/issues/798
> Link(s) to product …
> Update Develop your first integration page

- en/docs/reference/connectors/file-connector/file-connector-config.md
$Subject
Issue: https://github.com/wso2/docs-mi/issues/860
> Add sample configuration for file connector 4.x

- en/docs/install-and-setup/install/running-the-mi-in-automation-mode.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/913.
Updated UI:
> Resize image

- en/docs/assets/css/mitheme.css
This PR is to update the font size and color of the h4, h5, and h6.
Fixed the issue of `<h5>` and `<h6>` being smaller than the normal /`<p>` tag text.
Issue reference: https://github.com/wso2/docs-mi/issues/942
> Update header tag styling

- en/docs/reference/config-catalog-mi.md
$subject
Issue reference: https://github.com/wso2/docs-mi/issues/944
> [4.3.0] Remove PKCS12 from the possible values

- en/docs/reference/config-catalog-mi.md
$subject
Issue reference: https://github.com/wso2/docs-mi/issues/944
> [4.2.0] Remove PKCS12 from the possible values

- en/docs/reference/connectors/cdc-inbound-endpoint/cdc-inbound-endpoint-config.md
- en/docs/reference/connectors/db-event-inbound-endpoint/db-event-inbound-endpoint-config.md
- en/docs/reference/connectors/salesforce-connectors/sf-inbound-endpoint-reference-configuration.md
- en/docs/reference/connectors/smpp-connector/smpp-inbound-endpoint-config.md
This PR is to remove the CSS styling from the tables to make them consistent across the doc space. 
Issue reference: https://github.com/wso2/docs-mi/issues/51
> [4.3.0] Remove table styling

- en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/install.md
- en/docs/learn/examples/message-store-processor-examples/loadbalancing-with-message-processor.md
- en/docs/learn/examples/message-store-processor-examples/securing-message-processor.md
- en/docs/observe-and-manage/classic-observability-metrics/jmx-monitoring.md
- en/docs/reference/connectors/amazondynamodb-connector/amazondynamodb-connector-configuration.md
- en/docs/reference/connectors/amazondynamodb-connector/amazondynamodb-connector-reference.md
- en/docs/reference/connectors/amazonsqs-connector/1.x/amazonsqs-connector-1.x-example.md
- en/docs/reference/connectors/amazonsqs-connector/amazonsqs-inbound-endpoint-reference-configuration.md
- en/docs/reference/connectors/ceridiandayforce-connector/configuration/orgunitdetails.md
- en/docs/reference/connectors/google-pubsub-connector/googlepubsub-connector-example.md
- en/docs/reference/connectors/kafka-connector/kafka-connector-producer-example.md
- en/docs/reference/connectors/mongodb-connector/mongodb-connector-config.md
- en/docs/reference/connectors/salesforce-connectors/sf-rest-connector-config.md
This PR is to fix the issues with content tabs, admonitions, and code blocks not rendering properly.
Issue reference: https://github.com/wso2/docs-mi/issues/51
> [4.3.0] Fix formatting issues

- en/mkdocs.yml
$subject
This will fix https://github.com/wso2/docs-mi/issues/958.
> [4.2.0] Update theme names in tooltip text

- en/mkdocs.yml
$subject
This will fix https://github.com/wso2/docs-mi/issues/958.
> [4.3.0] Update theme names in tooltip text

- en/docs/reference/mediators/store-mediator.md
This is related to https://github.com/wso2/docs-mi/issues/937 …
> Refactor store mediator content

- en/docs/install-and-setup/setup/databases/setting-up-postgresql.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/857.
> [4.2.0] Add note on non-public schemas in PostgreSQL

- en/docs/install-and-setup/setup/databases/setting-up-postgresql.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/857.
> [4.3.0] Add note on non-public schemas in PostgreSQL

- en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/605.
> [4.3.0] Update setting-up-kafka.md

- .github/workflows/broken-link-checker.yml
> $subject
Fixes #278
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Add broken link checker

- en/docs/install-and-setup/upgrading-wso2-mi.md
> Update upgrading-wso2-mi.md MI Version Fix

- en/docs/learn/integration-tutorials/routing-requests-based-on-message-content.md
> Add references in tutorial

- en/docs/learn/integration-tutorials/exposing-several-services-as-a-single-service.md
> Corrected typo https://github.com/wso2/docs-mi/issues/461
> Correct a typo

- en/docs/reference/synapse-properties/expressions.md
This is to set functions as a separate topic …
> Update expression docs

- en/docs/develop/deploy-artifacts.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/987.
> Fix image alignment

- en/docs/get-started/development-kickstart.md
- en/docs/includes/build-and-run-artifacts.md
Remove content with the option to use the command MI: Build and Run to build and run a integration project
> Link(s) to product …
> Fix issue 986

- en/docs/develop/debugging-mediation.md
> Add a step to configure a fresh server in mediation debug docs
Fixes wso2/docs-mi/issues/830
> Add missing steps in mediation debug docs

- en/docs/develop/creating-unit-test-suite.md
Fix https://github.com/wso2/docs-mi/issues/994 …
> Add unit testing cli commands

- en/docs/index.md
- en/docs/reference/mediators/aggregate-mediator.md
- en/docs/reference/mediators/clone-mediator.md
- en/docs/reference/mediators/iterate-mediator.md
- en/docs/reference/mediators/store-mediator.md
This PR updates the old EIP references to direct to the updated content in the latest MI documentation.
> [4.2.0] Update EIP references

- en/docs/learn/examples/registry-examples/local-registry-entries.md
- en/mkdocs.yml
> Replace "Local registry entry" with "Local entry" since it can mislead the reader to create registry resources instead of local entries.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …
> Replace "registry" with "local entry"

- en/docs/install-and-setup/setup/deployment/deploying-micro-integrator-with-helm.md
> Add guide for deploying MI integrations on k8s using helm chart.

- en/docs/reference/connectors/google-ads-connector/google-ads-configuration.md
- en/docs/reference/connectors/google-ads-connector/google-ads-overview.md
> Add google ads audience APIs

- en/docs/reference/mediators/dss-mediator.md
> Improve the markdown formatting of the documentation for better readability and clarity. It also fixes a typo in the response log message.
> Enhance the structure and readability of the documentation.
> Ensured code blocks are correctly formatted. Fixed the typo in the sample response log to ensure accuracy in the documentation
> Type “Sent” when you have provided new/updated …
> Fix typos in doc dss-mediator.md

- en/docs/reference/mediators/cache-mediator.md
> Update cache mediator docs

- en/docs/learn/examples/registry-examples/local-registry-entries.md
- en/mkdocs.yml
$subject
This PR is to commit the changes done via https://github.com/wso2/docs-mi/pull/988 to the 4.3.0 branch.
> [4.3.0] Replace `registry` with `local entry`

- en/docs/reference/connectors/db-event-inbound-endpoint/db-event-inbound-endpoint-config.md
> Fix a typo

- en/docs/learn/examples/data-integration/distributed-trans-data-service.md
This PR is to remove the WIP note and fix an issue with the UI.
Fixes https://github.com/wso2/docs-mi/issues/405.
> [4.3.0] Update distributed-trans-data-service.md

- en/docs/develop/creating-artifacts/data-services/securing-data-services.md
- en/docs/get-started/quick-start-guide.md
- en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/install.md
- en/docs/learn/examples/data-integration/batch-requesting.md
- en/docs/learn/examples/data-integration/request-box.md
- en/docs/observe-and-manage/classic-observability-metrics/jmx-monitoring.md
- en/docs/reference/connectors/amazondynamodb-connector/amazondynamodb-connector-reference.md
- en/docs/reference/connectors/amazonsqs-connector/amazon-inbound-endpoint-1.0.x/amazonsqs-inbound-endpoint-reference-configuration.md
- en/docs/reference/connectors/amazonsqs-connector/amazonsqs-connector-config.md
- en/docs/reference/connectors/amazonsqs-connector/amazonsqs-inbound-endpoint-reference-configuration.md
- en/docs/reference/connectors/bigquery-connector/bigquery-connector-example.md
- en/docs/reference/connectors/ceridiandayforce-connector/configuration/orgunitdetails.md
- en/docs/reference/connectors/db-event-inbound-endpoint/db-event-inbound-endpoint-config.md
- en/docs/reference/connectors/google-pubsub-connector/googlepubsub-connector-example.md
- en/docs/reference/connectors/mongodb-connector/mongodb-connector-config.md
- en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
- en/docs/reference/connectors/redis-connector/redis-connector-example.md
- en/docs/reference/connectors/salesforce-connectors/sf-inbound-endpoint-reference-configuration.md
- en/docs/reference/connectors/salesforce-connectors/sf-rest-connector-config.md
- en/docs/reference/connectors/smpp-connector/smpp-inbound-endpoint-config.md
- en/docs/reference/connectors/smpp-connector/smpp-inbound-endpoint-example.md
- en/docs/reference/connectors/twitter-connector/twitter-connector-example.md
- en/docs/reference/mediators/db-report-mediator.md
- en/docs/reference/mediators/script-mediator.md
$subject
Issue reference: https://github.com/wso2/docs-mi/issues/51
> [4.2.0] Fix formatting issues

- en/docs/reference/connectors/salesforce-connectors/sf-inbound-endpoint-example.md
This is to fix https://github.com/wso2/docs-mi/issues/862 …
> Update salesforce inbound endpoint docs

- en/docs/reference/mediators/aggregate-mediator.md
- en/docs/reference/mediators/call-mediator.md
- en/docs/reference/mediators/clone-mediator.md
- en/docs/reference/mediators/data-mapper-mediator.md
- en/docs/reference/mediators/db-report-mediator.md
- en/docs/reference/mediators/dblookup-mediator.md
- en/docs/reference/mediators/dss-mediator.md
- en/docs/reference/mediators/ejb-mediator.md
- en/docs/reference/mediators/fastxslt-mediator.md
- en/docs/reference/mediators/filter-mediator.md
- en/docs/reference/mediators/header-mediator.md
- en/docs/reference/mediators/iterate-mediator.md
- en/docs/reference/mediators/json-transform-mediator.md
- en/docs/reference/mediators/loopback-mediator.md
- en/docs/reference/mediators/ntlm-mediator.md
- en/docs/reference/mediators/payloadfactory-mediator.md
- en/docs/reference/mediators/property-group-mediator.md
- en/docs/reference/mediators/property-mediator.md
- en/docs/reference/mediators/script-mediator.md
- en/docs/reference/mediators/send-mediator.md
- en/docs/reference/mediators/switch-mediator.md
- en/docs/reference/mediators/urlrewrite-mediator.md
- en/docs/reference/mediators/validate-mediator.md
- en/docs/reference/mediators/xquery-mediator.md
- en/docs/reference/mediators/xslt-mediator.md
This information is added in the about mediator page https://mi.docs.wso2.com/en/latest/reference/mediators/about-mediators/
> …
> Remove content-aware info from mediator pages

- en/docs/reference/mediators/throttle-mediator.md
This is related to https://github.com/wso2/docs-mi/issues/937 …
> Improve throttle mediator doc

- en/docs/reference/mediators/enrich-mediator.md
This is related to issue: https://github.com/wso2/docs-mi/issues/937
> Link(s) to product documentation that addresses the …
> Improve enrich mediator content

- en/docs/develop/using-wire-logs.md
- en/mkdocs.yml
This is to fix https://github.com/wso2/docs-mi/issues/1031
The mediatio level wire logs debugging support is not yet added in VS code plugin, once it is added as per the issue https://github.com/wso2/mi-vscode/issues/79 the removed content has to be added.
> Summary …
> Add use wire logs content

- en/docs/reference/connectors/connectors-overview.md
Replace the topic 'Types of connectors' to 'Categories of Connectors' This is to fix https://github.com/wso2/docs-mi/issues/1030
> Brief description of the new feature or bug fix as it will appear in the release …
> Fix issue 1030

- en/docs/reference/connectors/facebook-ads-connector/facebook-ads-configuration.md
- en/docs/reference/connectors/facebook-ads-connector/facebook-ads-overview.md
$title
Related: https://github.com/wso2-extensions/esb-connector-facebookads/pull/5
> Add facebookads user management APIs

- en/docs/install-and-setup/install/installation-options.md
- en/docs/install-and-setup/setup/deployment/kubernetes-deployment.md
> Update Helm repo urls

- en/docs/reference/mediators/property-group-mediator.md
- en/docs/reference/mediators/property-mediator.md
$subject
This is related to https://github.com/wso2/docs-mi/issues/936
> Link(s) to product documentation that addresses the …
> Improve property and property group mediator content

- en/docs/reference/connectors/google-ads-connector/google-ads-configuration.md
- en/docs/reference/connectors/google-ads-connector/google-ads-overview.md
> Add docs for user management APIs

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/improvement.yml
- .github/ISSUE_TEMPLATE/new-feature.yml
- .github/ISSUE_TEMPLATE/task.yml
> Add new issue template

- en/docs/get-started/introduction.md
- en/docs/get-started/quick-start-guide.md
This PR is for testing purposes.
> [Staging] Add canonical urls

- en/docs/get-started/introduction.md
- en/docs/get-started/quick-start-guide.md
- en/mkdocs.yml
>This PR is for testing purposes.
> Update canonical urls

- en/docs/reference/mediators/foreach-mediator.md
> Improve foreach mediator doc page

- en/docs/get-started/quick-start-guide.md
$subject
Issue reference: https://github.com/wso2/docs-mi/issues/1060
> Remove an invalid link

- en/docs/learn/examples/data-integration/batch-requesting.md
- en/docs/learn/examples/data-integration/request-box.md
This is to fix issue https://github.com/wso2/docs-mi/issues/1043
> Link(s) to product documentation that addresses the changes …
> Update issue 1043

- en/docs/reference/connectors/salesforce-connectors/sf-inbound-endpoint-reference-configuration.md
Update the reference documentation according to the UI schema. 
Fixes #632
> Update Salesforce Inbound Endpoint Reference Doc

- en/docs/reference/mediators/validate-mediator.md
$subject. This is related to issue https://github.com/wso2/docs-mi/issues/936
> Link(s) to product documentation that addresses …
> Improve validate mediator docs

- .github/workflows/weekly_sync_4.3.0_to_main.yaml
This is to add workflow to send sync PR from 4.3.0 branch to main
> Link(s) to product documentation that addresses the changes …
> Add workflow to send sync PR from 4.3.0 branch to main

- en/docs/develop/installing-wso2-integration-studio.md
- en/docs/develop/intro-integration-development.md
- en/docs/develop/working-with-service-catalog.md
This PR is to remove invalid references to the removed 'Develop your first integration' page.
> Remove invalid reference

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
This is to fix https://github.com/wso2/docs-mi/issues/809 …
> Add VFS properties content

- en/docs/reference/connectors/amazonsqs-connector/2.x/amazonsqs-connector-2.x-example.md
$subject for aws-core jar
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
> Update jar location

- en/docs/reference/connectors/smpp-connector/smpp-connector-config.md
> Update SMPP doc to include smscDeliveryReceipt

- en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
This is to fix https://github.com/wso2/docs-mi/issues/1083 …
> Add Health check be performed over HTTPS

- en/docs/develop/customizations/creating-custom-task-scheduling.md
This is to fix https://github.com/wso2/docs-mi/issues/1085 …
> Update backend service

- en/docs/install-and-setup/setup/brokers/configure-with-rabbitmq.md
- en/docs/install-and-setup/setup/performance-tuning/rabbitmq-transport-tuning.md
Add rabbitMQ proxy level throttling documentation
> Add rabbitMQ proxy level throttling

- en/mkdocs.yml
> Add Sharepoint connector to mkdocs.yml

- en/docs/get-started/quick-start-guide.md
This PR is to fix formatting issues in the QSG. (broken numbering caused by inserted images.)
> Fix formatting issues

- en/docs/get-started/quick-start-guide.md
This PR is to fix broken links on QSG.
> [4.3.0] Update QSG

- en/docs/learn/examples/rabbitmq-examples/point-to-point-rabbitmq.md
> Remove additional backend call since its not required to demonstrate the intended behaviour.
Fixes wso2/docs-mi/issues/675
> Remove additional backend call

- en/docs/learn/examples/rabbitmq-examples/request-response-rabbitmq.md
> Change log level in the proxy until we properly fix the issue. 
Related to wso2/docs-mi/issues/675
> Change log level

- en/docs/get-started/quick-start-guide.md
This PR is to update the staging site (testing purposes).
> [Staging] Update quick-start-guide.md

- en/docs/reference/connectors/smpp-connector/smpp-connector-config.md
This is to fix https://github.com/wso2/docs-mi/issues/1110 …
> Remove registredDelivery parameter

- en/docs/reference/connectors/iso8583-connector/iso8583-inbound-endpoint-config.md
Fixes: https://github.com/wso2/docs-mi/issues/634
> Update ISO8583 Inbound Endpoint Reference

- en/docs/reference/connectors/smpp-connector/smpp-inbound-endpoint-config.md
$subject
Resolves https://github.com/wso2/docs-mi/issues/647
> Update SMPP Inbound Endpoint Reference

- en/docs/observe-and-manage/classic-observability-logs/configuring-log4j2-properties.md
$subject
Resolves https://github.com/wso2/docs-mi/issues/981
Related PR https://github.com/wso2/wso2-synapse/pull/2185
> Update http access logs configuration

- en/docs/reference/troubleshooting/utilizing-runtime-diagnostic-tool.md
> Update runtime diagnostic tool enable/disable configuration

- en/docs/install-and-setup/setup/brokers/configure-with-weblogic.md
Fixes https://github.com/wso2/docs-mi/issues/961
> Update Web Logic server setup guide

- en/docs/learn/examples/template-examples/using-sequence-templates.md
Fix https://github.com/wso2/docs-mi/issues/1074 …
> Update sequence template example with optional params

- en/docs/reference/troubleshooting/error-handling-mi.md
This is related to https://github.com/wso2/docs-mi/issues/918 …
> Add DSS error codes in the troubelshooting section

- en/docs/develop/injecting-parameters.md
Fix https://github.com/wso2/docs-mi/issues/1073 …
> Fix issue 1073

- en/docs/reference/mediators/enrich-mediator.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/1142.
> [4.3.0] Update property name

- en/docs/reference/mediators/enrich-mediator.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/1142.
> [4.2.0] Update property name

- en/docs/install-and-setup/install/installing-integration-control-plane.md
This PR is to update the URL to the ICP.
> Fix invalid URL

- en/docs/install-and-setup/setup/brokers/configure-with-apache-artemis.md
$subject.
Fixes: https://github.com/wso2/docs-mi/issues/868
Updated doc:
> Configuring Address URI in a Sequence to Send a Message to a Queue in Artemis

- en/docs/reference/connectors/iso8583-connector/iso8583-connector-example.md
This is to fix https://github.com/wso2/docs-mi/issues/1140 …
> Fix issue 1140

- en/docs/reference/config-catalog-mi.md
This is to fix https://github.com/wso2/docs-mi/issues/863 …
> Fix issue 863

- en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
- en/docs/reference/connectors/mongodb-connector/mongodb-connector-overview.md
Related issue: This is to update the MongoDB connector documentation.
> Update the mongoDB connector guide

- en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
> Fix some formatting issues

- en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
> Add a new line to fix formatting

- en/docs/reference/synapse-properties/synapse-expressions.md
- en/mkdocs.yml
> Add docs for Synapse Expressions
Related to /issues/3749
> Add docs for Synapse Expressions

- en/docs/reference/mediators/about-mediators.md
- en/docs/reference/mediators/scatter-gather-mediator.md
- en/mkdocs.yml
Add Scatter Gather mediator docs
https://github.com/wso2/wso2-synapse/pull/2231
> Add Scatter Gather mediator docs

- en/docs/reference/mediators/payloadfactory-mediator.md
Update Payload Factory mediator for 4.4.0 version
https://github.com/wso2/wso2-synapse/pull/2236
> Update Payload Factory mediator for 4.4.0 version

- en/docs/reference/mediators/foreach-mediator.md
Update ForEach mediator for 4.4.0 version
https://github.com/wso2/wso2-synapse/pull/2252
> Update ForEach mediator for 4.4.0 version

- en/mkdocs.yml
This PR is to update the mkdocs.yml file for the 4.4.0 version.
> [4.4.0] Update site version

- en/theme/material/main.html
This PR is to add a WIP banner to the 4.4.0 doc space.
> [4.4.0] Add WIP banner

- en/docs/install-and-setup/install/installation-prerequisites.md
- en/docs/install-and-setup/setup/reference/product-compatibility.md
> Update tested OSs, DBs

- en/mkdocs.yml
$subject
Fixes https://github.com/wso2/docs-mi/issues/1044.
> [4.4.0] Exclude includes section from search

- en/mkdocs.yml
$subject
Fixes https://github.com/wso2/docs-mi/issues/1044.
> [4.3.0] Exclude includes section from search

- en/mkdocs.yml
$subject
Fixes https://github.com/wso2/docs-mi/issues/1044.
> [4.2.0] Exclude includes section from search

- en/docs/install-and-setup/setup/brokers/configure-with-activemq.md
- en/docs/reference/synapse-properties/transport-parameters/jms-transport-parameters.md
> $Subject
Fixes #1188
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Update compatible versions for ActiveMQ and JMS

- en/docs/install-and-setup/setup/brokers/configure-with-activemq.md
- en/docs/reference/synapse-properties/transport-parameters/jms-transport-parameters.md
> $Subject
Fixes https://github.com/wso2/docs-mi/issues/1188 …
> [4.4.0] Update compatible versions of ActiveMQ

- en/theme/material/main.html
This PR is to add a WIP banner to the 4.4.0 doc space.
Issue reference: https://github.com/wso2/docs-mi/issues/1179
> [main] Add WIP banner

- en/mkdocs.yml
This PR is to update the mkdocs.yml file for the 4.4.0 version.
Issue reference: https://github.com/wso2/docs-mi/issues/1179
> [main] Update site version

- en/docs/install-and-setup/setup/transport-configurations/multi-https-transport.md
This PR is to fix a formatting issue on the page that causes a configuration to be missing on the UI.
Fixes https://github.com/wso2/docs-mi/issues/1230.
> [main] Update multi-https-transport.md

- en/docs/install-and-setup/setup/transport-configurations/multi-https-transport.md
This PR is to fix a formatting issue on the page that causes a configuration to be missing on the UI.
Fixes https://github.com/wso2/docs-mi/issues/1230.
> [4.2.0] Update multi-https-transport.md

- en/docs/install-and-setup/setup/transport-configurations/multi-https-transport.md
This PR is to fix a formatting issue on the page that causes a configuration to be missing on the UI.
Fixes https://github.com/wso2/docs-mi/issues/1230.
> [4.3.0] Update multi-https-transport.md

- en/docs/install-and-setup/setup/message-builders-formatters/message-relay.md
This PR is to add the missing content.
Fixes https://github.com/wso2/docs-mi/issues/904.
> [4.3.0] Update message-relay.md

- en/docs/install-and-setup/setup/message-builders-formatters/message-relay.md
This PR is to add the missing content.
Fixes https://github.com/wso2/docs-mi/issues/904.
> [4.2.0] Update message-relay.md

- en/docs/reference/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md
This PR is to add RabbitMQ publisher confirms support.
Fixes https://github.com/wso2/docs-mi/issues/1204.
> [4.3.0] Update rabbitmq-transport-parameters.md

- en/docs/reference/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md
This PR is to add RabbitMQ publisher confirms support.
Fixes https://github.com/wso2/docs-mi/issues/1204.
> [4.2.0] Update rabbitmq-transport-parameters.md

- en/docs/develop/working-with-service-catalog.md
- en/mkdocs.yml
> Add Publishing Integrations to the API Manager page

- en/docs/reference/connectors/kafka-connector/kafka-connector-producer-example.md
> Fix missing backtick for the KAFKA_HOME variable path

- en/docs/learn/examples/rest-api-examples/introduction-rest-api.md
> Update "How to Use a Simple REST API" Doc 

- en/docs/learn/examples/rest-api-examples/setting-query-params-outgoing-messages.md
Update the documentation with new expression support.
> Update "How to Set Query Parameters on Outgoing Messages" Doc

- en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
> [4.3.0] Fix a formatting issue

- en/docs/learn/examples/data-integration/mongo-data-service.md
> Update the MongoDb docs

- en/docs/reference/mediators/variable-mediator.md
Update variable mediator docs
Fixes: https://github.com/wso2/docs-mi/issues/1258
> Update variable mediator docs

- en/mkdocs.yml
This PR is to restructure the site navigation:
- navbar
- left sidebar for the `Reference` section
**Current Navbar**
**Proposed Navbar**
**Current Left Sidebar of the `References` section**
**Proposed Left Sidebar of the `References` section**
> [4.4.0] Restructure site navigation

- en/docs/learn/enterprise-integration-patterns/message-routing/dynamic-router.md
- en/docs/learn/enterprise-integration-patterns/message-routing/message-filter.md
- en/docs/learn/enterprise-integration-patterns/message-transformation/claim-check.md
- en/docs/learn/enterprise-integration-patterns/message-transformation/normalizer.md
- en/docs/learn/enterprise-integration-patterns/messaging-channels/message-bus.md
- en/docs/learn/enterprise-integration-patterns/messaging-systems/pipes-and-filters.md
- en/docs/learn/enterprise-integration-patterns/system-management/detour.md
- en/docs/learn/enterprise-integration-patterns/system-management/test-message.md
- en/docs/learn/samples/message-filtering.md
- en/docs/reference/mediators/about-mediators.md
- en/docs/reference/mediators/call-mediator.md
- en/docs/reference/mediators/fault-mediator.md
- en/docs/reference/mediators/filter-mediator.md
Rename filter mediator to if else mediator
https://github.com/wso2-enterprise/mi-language-server/pull/251
> Rename filter mediator to if else mediator

- en/docs/reference/synapse-properties/synapse-expressions.md
> Add content for accessing config parameters

- en/docs/reference/connectors/file-connector/file-connector-config.md
> Update file connector-SMB config

- en/docs/learn/examples/inbound-endpoint-examples/inbound-endpoint-mqtt-protocol.md
>  Fix https://github.com/wso2/docs-mi/issues/1282  …
> Fix MQTT Inbound Endpoint examples issue

- en/docs/learn/samples/fetch-salesforce.md
> Update "Salesforce" sample doc

- en/docs/reference/connectors/cdc-inbound-endpoint/cdc-inbound-endpoint-config.md
> Update CDC inbound EP with preserve.event paramater

- en/docs/learn/examples/inbound-endpoint-examples/inbound-endpoint-hl7-protocol-auto-ack.md
> Fix: https://github.com/wso2/docs-mi/issues/1279 …
> Fix for removing invalid elements from sequence sample in HL7

- en/docs/install-and-setup/setup/brokers/configure-with-apache-artemis.md
> Update the "configure with Apache Artemis" doc and update the latest supported version

- en/docs/install-and-setup/install/installing-integration-control-plane.md
- en/docs/install-and-setup/install/running-the-integration-control-plane.md
- en/docs/install-and-setup/setup/user-stores/setting-up-a-userstore-in-mi.md
- en/docs/observe-and-manage/working-with-integration-control-plane.md
> Update ICP docs

- en/docs/assets/attachments/quick-start-guide/quick-start-guide.iml
- en/docs/develop/externalized-configuration.md
- en/docs/develop/using-embedded-micro-integrator.md
- en/docs/install-and-setup/setup/dynamic-server-configurations.md
- en/docs/reference/synapse-properties/endpoint-properties.md
> Update doc and rename the file

- en/docs/learn/examples/rest-api-examples/introduction-rest-api.md
> Update "How to Use a Simple REST API"doc by replacing term `uriParams` with `pathParams`

- en/docs/observe-and-manage/managing-integrations-with-micli.md
- en/docs/observe-and-manage/working-with-management-api.md
Related feature PR: https://github.com/wso2/product-micro-integrator/pull/3823
> Add docs for inbound endpoint activate/deactivate feature

- en/docs/observe-and-manage/managing-integrations-with-micli.md
- en/docs/observe-and-manage/working-with-management-api.md
> Update manamgement API and CLI docs

- en/docs/observe-and-manage/managing-integrations-with-micli.md
> Update Inbound Endpoint CLI docs

- en/docs/reference/connectors/http-connector/http-connector-example.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/1363.
> [4.4.0] Fix formatting issues

- en/docs/learn/examples/registry-examples/local-registry-entries.md
> Update local entry example doc

- en/docs/install-and-setup/install/installation-prerequisites.md
> Update installation prerequisites for compatibility with new OS and database versions

- en/docs/reference/connectors/http-connector/http-connector-example.md
> Update handling certificates in HTTP connector example doc

- en/docs/learn/examples/data-integration/batch-requesting.md
enableBatchRequests="true" flag is missing
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
> Add missing config in batch req doc

- en/docs/install-and-setup/setup/brokers/configure-with-rabbitmq.md
> Change rabbitmq throttling mode fixed-interval to fixed_interval

- en/docs/reference/mediators/iterate-mediator.md
$subject to fix https://github.com/wso2/docs-mi/issues/1398 …
> Add iterate mediator clonning info

- en/docs/assets/versions.json
> Update 4.4.0 link to latest

- en/docs/reference/mediators/iterate-mediator.md
> Fix broken link

- en/docs/learn/integration-tutorials/sap-integration.md
- en/mkdocs.yml
Add SAP Integration doc to Learn section
> Add SAP Integration doc to Learn section

- en/theme/material/404.html
- en/theme/material/main.html
Push 404 error logs to analytics
> Push 404 error logs to analytics

- en/docs/install-and-setup/setup/brokers/configure-with-rabbitmq.md
$subject
Issue reference: https://github.com/wso2/docs-mi/issues/1346
> [4.3.0] Add RabbitMQ throttling parameters

- en/docs/install-and-setup/setup/brokers/configure-with-rabbitmq.md
$subject
Issue reference: https://github.com/wso2/docs-mi/issues/1346
> [4.4.0] Add RabbitMQ throttling parameters

- en/docs/reference/mediators/script-mediator.md
> Add rhinoJs config to script mediator

- en/docs/reference/mediators/throw-error-mediator.md
> Fix syntax error in ThrowError mediator
> Fix syntax error in ThrowError mediator

- en/docs/includes/create-new-project.md
- en/docs/includes/setting-up-workspace-for-mi-for-vscode.md
- en/docs/install-and-setup/install/installation-prerequisites.md
- en/docs/install-and-setup/setup/brokers/configure-with-weblogic.md
- en/docs/install-and-setup/upgrading-wso2-mi.md
- en/docs/observe-and-manage/managing-integrations-with-micli.md
This PR replaces 4.3.0 with 4.4.0.
Issue reference: https://github.com/wso2/docs-mi/issues/1362
> Update MI version

- en/docs/reference/mediators/log-mediator.md
- en/docs/reference/mediators/scatter-gather-mediator.md
Update Log and Scatter Gather mediator reference docs
Fixes: https://github.com/wso2/docs-mi/issues/1412
Fixes: https://github.com/wso2/docs-mi/issues/1383
> Update Log and Scatter Gather mediator reference docs

- en/docs/reference/mediators/iterate-mediator.md
Add content to mention aggregate mediator is not needed when ou-only in iterate mediator
> Link(s) to product documentation …
> Iterate mediator out only content

- en/docs/assets/css/mitheme.css
Add border around images
Fixes: https://github.com/wso2/docs-mi/issues/1431
> Add border around images

- en/docs/assets/js/mitheme.js
- en/docs/index.md
Revamp home page
Fixes: https://github.com/wso2/docs-mi/issues/1353
> Revamp home page

- en/docs/develop/installing-wso2-integration-studio.md
- en/docs/develop/troubleshooting-wso2-integration-studio.md
- en/docs/develop/working-with-wso2-integration-studio.md
- en/docs/develop/wso2-integration-studio.md
Add Studio deprecation note
Fixes: https://github.com/wso2/docs-mi/issues/1440
> Add Studio deprecation note

- en/docs/assets/js/mitheme.js
Update GA4 event data for search
> Update GA4 event data for search

- en/docs/get-started/how-to-guides/ai-code-generation.md
- en/docs/get-started/how-to-guides/ai-data-mapping.md
Add Youtube links to how-to guide docs
> Add Youtube links to how-to guide docs

- en/docs/assets/css/blue-palette-alt1.css
- en/docs/assets/css/config-catalog.css
- en/docs/assets/css/mitheme.css
- en/mkdocs.yml
Update link and header styles
Fixes: https://github.com/wso2/docs-mi/issues/1443
**Current UI:**
**Updated UI:**
> Update link and header styles

- en/docs/get-started/how-to-guides/ai-data-mapping.md
Improve Data Mapping using AI guide
Fixes: https://github.com/wso2/docs-mi/issues/1450
> Improve Data Mapping using AI guide

- en/docs/assets/js/mitheme.js
- en/theme/material/base.html
- en/theme/material/main.html
> Update Google tag

- en/docs/install-and-setup/setup/deployment/deploying-micro-integrator-with-helm.md
> Fix tip rendering issues

- en/docs/assets/js/mitheme.js
- en/theme/material/base.html
> Add CookiePro consent

- en/theme/material/base.html
Add CookiePro consent
https://github.com/wso2/docs-mi/issues/1469
> [4.2.0] Add CookiePro consent

- en/theme/material/base.html
Add CookiePro consent
https://github.com/wso2/docs-mi/issues/1469
> [4.3.0] Add CookiePro consent

- en/docs/index.md
Add the `Install & Setup` tile to the home page
> Add the Install & Setup tile to the home page

- en/docs/install-and-setup/install/icp-installation-prerequisites.md
- en/docs/install-and-setup/install/installation-prerequisites.md
- en/docs/install-and-setup/install/installing-integration-control-plane.md
- en/mkdocs.yml
> Add ICP installation prerequisites

- en/docs/mi-analytics/mi-custom-analytics.md
- en/mkdocs.yml
$ subject
Issue - https://github.com/wso2-enterprise/wso2-mi-internal/issues/995
MI PR - https://github.com/wso2/product-micro-integrator/pull/4078
This is how the new documentation will look in the UI. …
> Add custom analytics documentation

- en/docs/install-and-setup/install/installation-prerequisites.md
> Update installation prerequisites

- en/docs/mi-analytics/mi-custom-analytics.md
Corrects `enable`-> `enabled` in `[analytics]` table of the deployment.toml
> Link to the PR for changes to the training content …
> Fix typo in custom analytics page

- en/docs/install-and-setup/setup/deployment/deploying-wso2-mi.md
Update the documentation on `Configuring a Micro Integrator Cluster` by adding a section on `Monitoring the cluster with ICP`.
> Add documentation on monitoring a MI cluster with ICP

- en/docs/reference/connectors/file-connector/file-connector-config.md
> Update file connector-SMB config with encodePassword

- en/docs/reference/connectors/file-connector/file-connector-config.md
> Update file connector-SMB configs

- en/docs/reference/connectors/file-connector/file-connector-config.md
- en/docs/reference/mediators/property-reference/http-transport-properties.md
Add diskShareAccessMask documentation for File Connector and update HTTP transport FORCE_SC_ACCEPTED description
> Add documentation for configure Access mask for disk share

- en/docs/install-and-setup/install/installation-prerequisites.md
> Update installation prerequisites for Red Hat Enterprise Linux to version 9.5

- en/docs/reference/connectors/file-connector/file-connector-config.md
> Fix formatting in File connector

- en/docs/assets/css/config-catalog.css
- en/docs/install-and-setup/setup/brokers/configure-with-rabbitmq.md
- en/docs/install-and-setup/setup/performance-tuning/rabbitmq-transport-tuning.md
- en/docs/reference/config-catalog-integration-control-plane.md
- en/docs/reference/config-catalog-mi.md
- en/docs/reference/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md
This PR fixes the following issues,
1. View Sample/Hide Sample toggle issue in config catalog docs. Fixes: https://github.com/wso2/docs-mi/issues/102
https://github.com/user-attachments/assets/a7138174-f994-45f6-8a5c-c2e5fa21ff05
2. Remove unused parameters in **RabbitMQ Sender** config docs.
3. Add missing parameters in **RabbitMQ Sender** config docs.
4. Update `Required` and `default` values in **RabbitMQ Sender** and **RabbitMQ Listener** config docs
Fixes: https://github.com/wso2/docs-mi/issues/1503
> Update RabbitMQ sender and listener config catalog docs 

- en/mkdocs.yml
> Update 4.4.0 staging doc url

- en/mkdocs.yml
Update base path for 4.4.0 staging docs
> Update base path for 4.4.0 staging docs

- en/mkdocs.yml
> Fix email connector 1.x page

- en/docs/reference/connectors/csv-module/csv-module-config.md
> Add note about required opencsv jar for CSV Module 2.x.x

- en/docs/learn/enterprise-integration-patterns/message-transformation/canonical-data-model.md
- en/docs/learn/enterprise-integration-patterns/message-transformation/claim-check.md
- en/docs/learn/enterprise-integration-patterns/messaging-channels/messaging-bridge.md
- en/docs/learn/enterprise-integration-patterns/messaging-systems/message-translator.md
- en/docs/learn/examples/json-examples/json-examples.md
- en/docs/learn/examples/message-transformation-examples/json-to-soap-conversion.md
- en/docs/learn/examples/message-transformation-examples/pox-to-json-conversion.md
- en/docs/learn/examples/rest-api-examples/enabling-rest-to-soap.md
- en/docs/learn/integration-tutorials/exposing-several-services-as-a-single-service.md
- en/docs/learn/samples/content-based-routing.md
- en/docs/learn/samples/header-based-routing.md
- en/docs/reference/connectors/amazonsqs-connector/1.x/amazonsqs-connector-1.x-example.md
- en/docs/reference/connectors/amazonsqs-connector/2.x/amazonsqs-connector-2.x-example.md
- en/docs/reference/connectors/connector-usage.md
- en/docs/reference/connectors/connectors-overview.md
- en/docs/reference/connectors/email-connector/1.x/email-connector-1.x-example.md
- en/docs/reference/connectors/email-connector/email-connector-example.md
- en/docs/reference/connectors/redis-connector/redis-connector-example.md
- en/docs/reference/connectors/salesforce-connectors/sf-soap-connector-example.md
- en/docs/reference/mediators/about-mediators.md
- en/docs/reference/mediators/call-mediator.md
- en/docs/reference/mediators/loopback-mediator.md
- en/docs/reference/mediators/payloadfactory-mediator.md
- en/docs/reference/mediators/property-mediator.md
- en/docs/reference/mediators/property-reference/generic-properties.md
- en/docs/reference/mediators/property-reference/http-transport-properties.md
- en/docs/reference/mediators/property-reference/soap-headers.md
- en/docs/reference/mediators/sequence-mediator.md
- en/docs/reference/mediators/validate-mediator.md
Rename 'PayloadFactory' to Payload mediator
Fixes: https://github.com/wso2/docs-mi/issues/1482
> Rename 'PayloadFactory' to Payload mediator

- en/mkdocs.yml
Fix Kafka example doc redirect issue
> Fix Kafka example doc redirect issue

- en/docs/install-and-setup/setup/brokers/configure-with-apache-artemis.md
> Add a note to explaining the maximum connector jar version we can use with MI
> Add artemis connector jar info

- en/mkdocs.yml
> Fix redirect link issue

- en/docs/assets/css/blue-palette-alt1.css
Fix button colour in dark mode
> Fix button colour in dark mode

- en/docs/reference/connectors/file-connector/file-connector-config.md
> Update file connector configs with diskShareAccessMask
> [4.4.0] Update file connector configs with diskShareAccessMask 

- en/docs/reference/connectors/file-connector/file-connector-config.md
> Update file connector configs with diskShareAccessMask
> [4.2.0]Update file connector configs with diskShareAccessMask

- en/docs/index.md
- en/mkdocs.yml
Revert 'Build your first integration'
> Revert 'Build your first integration'

- en/docs/includes/build-and-run-artifacts.md
Remove MI setup steps from Build and run include
> Remove MI setup steps from Build and run include

- en/docs/reference/connectors/file-connector/file-connector-config.md
> update file connector version

- en/docs/develop/customizations/ballerina-module/overview.md
Fix this numbering issue in [Ballerina Module doc](https://mi.docs.wso2.com/en/latest/develop/customizations/ballerina-module/overview/)
> Fix ord-list numbering in BallerinaModule

- en/docs/reference/connectors/salesforce-pubsub-connector/sf-pubsub-example.md
> Update the event creation step

- en/docs/observe-and-manage/setting-up-cloud-native-observability-in-kubernetes.md
> Update documentation on Setting up Grafana based Observability on Kubernetes

- en/docs/administer/logging-and-monitoring/logging/managing-log-growth.md
> Update doc for managing log growth

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
> Add missing FileSortAttribute
> Add missing FileSortAttribute

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
> Add missing FileSortAttribute parameter
> Add missing FileSortAttribute param

- en/docs/reference/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md
> Update RabbitMQ publisher confirms documentation

- en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-config.md
> Add docs for manual offset committing in Kafka Inbound Endpoint

- en/docs/reference/connectors/kafka-connector/kafka-connector-config.md
> Update Kafka connector docs

- en/docs/install-and-setup/setup/transport-configurations/multi-https-transport.md
$subject
Related: https://github.com/wso2/product-micro-integrator/issues/4141
> Add client-based SSL for Multi-HTTPS sender docs

- en/docs/learn/examples/transport-examples/tcp-transport-examples.md
> Add doc changes for new parameters in TCP transport 
Related to wso2/product-micro-integrator/issues/4231
> Add doc changes for TCP transport

- en/docs/install-and-setup/setup/transport-configurations/multi-https-transport.md
> Fix property name in SSL profiles for the Multi-HTTPS

- en/docs/reference/connectors/connector-tools/grpc/grpc-connector-overview.md
> Reset title alignments in connector page

- en/docs/reference/connectors/google-ads-connector/google-ads-configuration.md
- en/docs/reference/connectors/google-ads-connector/google-ads-overview.md
$Subject
Issue: https://github.com/wso2/product-micro-integrator/issues/4222
> Update google ads connector doc

- en/docs/install-and-setup/setup/performance-tuning/rabbitmq-transport-tuning.md
> Add section on tuning RabbitMQ connection pool parameters

- en/docs/install-and-setup/setup/performance-tuning/rabbitmq-transport-tuning.md
> Refactor RabbitMQ connection pool parameters for clarity and consistency

- en/docs/install-and-setup/setup/performance-tuning/rabbitmq-transport-tuning.md
> fix issue with Tune RabbitMQ Connection Pool Parameters

- en/docs/reference/connectors/iso8583-connector/iso8583-connector-configuration.md
<PRODUCT_HOME>/repository/components/lib -> <MI_HOME>/lib …
> Fix wrong folder path

- en/docs/install-and-setup/install-and-setup-overview.md
> Fixes minor typographical errors, grammar issues in the Micro Integrator module. Improves documentation readability and maintains formatting consistency.
> Ensure documentation is free from typos and grammar mistakes.
> Removed duplicated words (e.g., "to to")
> Rephrased incorrect grammar ("and well as" → "as well as")
> Changes are made only to .md files; no UI changes involved.
> As a contributor or reader, I want to read clear, consistent, and professionally written documentation.
> Fixed typos, grammar issues, and formatting inconsistencies in Micro Integrator documentation pages.
> This PR directly modifies the documentation under the following area
-  en/docs/install-and-setup/install-and-setup-overview.md
> N/A for additional external doc links as changes are internal to this …
> Update install-and-setup-overview.md  to fix correct typos

- en/docs/reference/mediators/class-mediator.md
Update class mediator docs with expression limitations
> Update class mediator docs with expression limitations

- en/docs/install-and-setup/setup/brokers/configure-with-rabbitmq.md
- en/docs/install-and-setup/setup/performance-tuning/rabbitmq-transport-tuning.md
- en/docs/learn/examples/rabbitmq-examples/request-response-rabbitmq.md
>  Add RabbitMQ parameter changes
Related to wso2/product-micro-integrator/issues/4290
> Add RabbitMQ parameter changes

- en/docs/reference/mediators/xslt-mediator.md
> porting wso2/docs-mi/pull/1244
> Update docs for optimizing the XSLT mediator

- en/docs/reference/mediators/call-mediator.md
- en/docs/reference/mediators/property-reference/axis2-properties.md
> Add description for DISABLE_COOKIE property
> Add description for DISABLE_COOKIE property

- en/docs/reference/mediators/clone-mediator.md
> Update clone mediator syntax

- en/docs/reference/mediators/script-mediator.md
$subject: removing limitation section
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
> Update script mediator docs

- en/docs/reference/connectors/file-connector/file-connector-overview.md
Add a Prerequisites section to the file connector to address https://github.com/wso2/product-micro-integrator/issues/4319
> Update file connector documentation

- en/docs/reference/connectors/file-connector/file-connector-config.md
- en/docs/reference/connectors/file-connector/file-connector-overview.md
Add a Prerequisites section to the file connector to address https://github.com/wso2/product-micro-integrator/issues/4319
> [4.2.0]Update file connector documentation

- en/docs/reference/connectors/as400-pcml-connector/as400-pcml-connector-configuration.md
- en/docs/reference/connectors/as400-pcml-connector/as400-pcml-connector-reference.md
- en/mkdocs.yml
This is to fix https://github.com/wso2/docs-mi/issues/1711 …
> Add AS400 PCML connector

- en/docs/get-started/about-this-release.md
- en/docs/get-started/event-driven-integrations.md
- en/docs/install-and-setup/install/installation-prerequisites.md
- en/docs/install-and-setup/upgrading-wso2-mi.md
- en/docs/reference/connectors/ai-module/ai-module-overview.md
- en/docs/reference/connectors/amazondynamodb-connector/amazondynamodb-connector-overview.md
- en/docs/reference/connectors/amazonlambda-connector/amazonlambda-connector-overview.md
- en/docs/reference/connectors/connector-tools/grpc/grpc-connector-overview.md
- en/docs/reference/connectors/email-connector/email-connector-overview.md
- en/docs/reference/connectors/file-connector/file-connector-overview.md
- en/docs/reference/connectors/generate-connectors.md
- en/docs/reference/connectors/gmail-connector/gmail-connector-overview.md
- en/docs/reference/connectors/google-ads-connector/google-ads-overview.md
- en/docs/reference/connectors/google-pubsub-connector/googlepubsub-connector-overview.md
- en/docs/reference/connectors/http-connector/http-connector-overview.md
- en/docs/reference/connectors/idp-connector/idp-connector-overview.md
- en/docs/reference/connectors/iso8583-connector/iso8583-connector-overview.md
- en/docs/reference/connectors/jira-connector/jira-connector-overview.md
- en/docs/reference/connectors/mongodb-connector/mongodb-connector-overview.md
- en/docs/reference/connectors/msazuredatalakestorage-connector/microsoft-azure-data-lake-storage-connector-overview.md
- en/docs/reference/connectors/pulsar-connector/pulsar-connector-overview.md
- en/docs/reference/connectors/salesforce-pubsub-connector/sf-pubsub-overview.md
- en/docs/reference/connectors/servicenow-connector/servicenow-overview.md
- en/docs/reference/connectors/smpp-connector/smpp-connector-overview.md
- en/docs/reference/connectors/twitter-connector/twitter-connector-overview.md
> Update MI version and about this release page

- en/docs/reference/mediators/call-mediator.md
- en/docs/reference/mediators/property-reference/axis2-properties.md
Add description for DISABLE_COOKIE property in call mediator and axis2 properties docs.
(cherry picked from commit 2b1a2c0597955bc2ebbef61afa61695657550cc3)
> Add description for DISABLE_COOKIE property for MI 4.3.0 Docs

- en/docs/reference/mediators/call-mediator.md
- en/docs/reference/mediators/property-reference/axis2-properties.md
Add description for DISABLE_COOKIE property in call mediator and axis2 properties docs.
(cherry picked from commit 2b1a2c0597955bc2ebbef61afa61695657550cc3)
> Add description for DISABLE_COOKIE property for MI 4.2.0 Docs

- en/docs/develop/customizations/creating-new-connector.md
Update Maven command to generate connector template using the latest archetype version.
> Update create a new connector documentation

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
> Update Amazon S3 getObject property: escapeXmlCharacters

- en/docs/reference/config-catalog-mi.md
> Update transport.blocking.rabbitmq.sender configs

- en/docs/install-and-setup/setup/deployment/deploying-wso2-mi.md
Updated the path for the deployment.toml file location in the WSO2 MI deployment documentation.
> Link(s) to product …
> Correct deployment.toml file path in documentation

- .github/workflows/auto_lable.yml
Skip adding AI-Agent/Queued label if that issue has an assignee or is in Hacktoberfest project
> Skip labelling if issue has an assignee or is in Hacktoberfest project

- en/docs/develop/mi-for-vscode/best-practices.md
- en/mkdocs.yml
This pull request introduces a comprehensive "Best Practices Guide" for WSO2 Micro Integrator (MI) development.
> Add initial draft of best practices guide
