wso2/docs-mi

en/docs/reference/config-catalog-mi.md

The following needs to updated in the https://apim.docs.wso2.com/en/latest/reference/config-catalog-mi/#https-transport-non-blocking-mode page,
The HTTP transport keystores (https://apim.docs.wso2.com/en/latest/reference/config-catalog-mi/#https-transport-non-blocking-mode)
listener.keystore.file_name --> listener.keystore.location
sender.keystore.file_name --> sender.keystore.location
listener.truststore.file_name -- > listener.truststore.location
sender.truststore.file_name --> sender.truststore.location
Management API configs (https://apim.docs.wso2.com/en/latest/reference/config-catalog-mi/#management-api-cors)
Need to have only single square bracket for the below property
[[management_api.cors]] --> [management_api.cors]
Possible Values under allowed_origins should be "any string" …

Fix misconfigurations in MI config catalog doc

---

en/theme/material/customizations.md
en/theme/material/partials/tabs-item.html

This PR is to remove the separation done to the top navigation bar. 
This modification, originally present in the APIM documentation, is unnecessary in the MI documentation. Therefore removing it via this PR.

Remove navigation separation

---

en/docs/install-and-setup/setup/message-builders-formatters/message-builders-and-formatters.md

This PR is to fix an error in the `custom_message_formatters` config.
Issue reference: https://github.com/wso2/docs-apim/issues/7556

[4.2.0] Update message-builders-and-formatters.md

---

en/docs/install-and-setup/setup/message-builders-formatters/message-builders-and-formatters.md

This PR is to fix an error in the `custom_message_formatters` config.
Issue reference: https://github.com/wso2/docs-apim/issues/7556

[Main] Update message-builders-and-formatters.md

---

en/theme/material/partials/copyright.html

fixes https://github.com/wso2/docs-mi/issues/73
Updated the year mentioned in the copyrights statement.
- WSO2 generally follows the standard of adding the year of the copyrights based on the initial year the documentation was created to the current year (e.g., [1]). Therefore, I updated the copyrights year in this manner as opposed to just mentioning 2024.
[1] https://is.docs.wso2.com/en/5.11.0/
https://github.com/wso2/docs-mi/issues/73
@DinithiDiaz 
@Mariangela

[main] Update copyrights

---

en/theme/material/partials/copyright.html

fixes https://github.com/wso2/docs-mi/issues/73
Updated the year mentioned in the copyrights statement.
- WSO2 generally follows the standard of adding the year of the copyrights based on the initial year the documentation was created to the current year (e.g., [1]). Therefore, I updated the copyrights year in this manner as opposed to just mentioning 2024.
[1] https://is.docs.wso2.com/en/5.11.0/
https://github.com/wso2/docs-mi/issues/73
@Mariangela 
@DinithiDiaz

[4.2.0] Update copyrights

---

en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md

This PR is to add the missing info on auto reloading of `file.properties`.
https://github.com/wso2/docs-apim/pull/4252

[4.2.0] Add info on auto reloading of file.properties

---

en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md

This PR is to add the missing info on auto reloading of `file.properties`.
https://github.com/wso2/docs-apim/pull/4252

[4.3.0] Add info on auto reloading of file.properties

---

en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md

This PR is to add the missing info on auto reloading of `file.properties`.
https://github.com/wso2/docs-apim/pull/4252

[main] Add info on auto reloading of file.properties

---

en/docs/reference/mediators/property-reference/http-transport-properties.md

This PR is to update the doc with the `NON_ERROR_HTTP_STATUS_CODES` property.
https://github.com/wso2/docs-apim/pull/4002/

[4.2.0] Update documentation on non.error.http.status.code property

---

en/docs/reference/mediators/property-reference/http-transport-properties.md

This PR is to update the doc with the `NON_ERROR_HTTP_STATUS_CODES` property.
https://github.com/wso2/docs-apim/pull/4002/

[4.3.0] Update documentation on non.error.http.status.code property

---

en/docs/reference/mediators/property-reference/http-transport-properties.md

This PR is to update the doc with the `NON_ERROR_HTTP_STATUS_CODES` property.
https://github.com/wso2/docs-apim/pull/4002/

[main] Update documentation on non.error.http.status.code property

---

en/theme/material/base.html

This PR is to add a `noindex` and `nofollow` tags to the 4.3.0 doc space to prevent search engine crawlers from indexing the documentation site. This change is necessary because there are multiple WIP pages that should not be visible in search results. 
**Reference:** 
- https://squidfunk.github.io/mkdocs-material/reference/?h=robots#on-all-pages
- https://developers.google.com/search/docs/crawling-indexing/block-indexing

[4.3.0] Add `noindex` and `nofollow` tags to prevent crawlers from indexing WIP pages

---

en/docs/learn/samples/database-polling.md
en/docs/learn/samples/rest-data-service.md
en/docs/learn/samples/students-data-service.md

This PR removes the instruction to download and add the mysql-connector to the project as the samples were updated to download the relevant dependencies.

Updating dataservice sample projects related documentation

---

en/docs/assets/css/mitheme.css
en/docs/assets/js/mitheme.js
en/theme/material/partials/header.html

This PR is to add the custom dropdown component to fetch and display the doc versions, its functionalities and style adjustments.
---
---
- It includes a code block to temporarily hide the dropdown from the UI until the next release. [Added via [606293b](https://github.com/wso2/docs-mi/commit/606293b0b4eb20eeeef457e0b7528de4000cfa2b)] Hence, until it is removed, the dropdown will remain hidden.
- It also includes a fix to maintain the URL path when switching between versions (to remain on the same page when switching the versions).

[4.2.0] Add custom dropdown component

---

en/docs/assets/css/mitheme.css
en/docs/assets/js/mitheme.js
en/theme/material/partials/header.html

This PR is to add the custom dropdown component to fetch and display the doc versions, its functionalities and style adjustments.
---
---
- It includes a code block to temporarily hide the dropdown from the UI until the next release. [Added via [864803b](https://github.com/wso2/docs-mi/commit/864803b9e0eb7f7bb015ffdf22f09b7a67e2ac60)] Hence, until it is removed, the dropdown will remain hidden.
- It also includes a fix to maintain the URL path when switching between versions (to remain on the same page when switching the versions).

[4.3.0] Add custom dropdown component

---

en/mkdocs.yml

This PR is to add Event Message and Message Bus pages to the left sidebar of the docs site.
Related: https://github.com/wso2/docs-mi/pull/827

[4.3.0] Update mkdocs.yml

---

en/theme/material/base.html

This PR is to remove the `noindex` and `nofollow` tags from the MI 4.3.0 doc space.

[4.3.0] Remove `noindex` and `nofollow` tags 

---

en/docs/install-and-setup/setup/deployment/deploying-micro-integrator-with-helm.md

- Update document to MI 4.3.0
- Removed `What's next` part because the content removed from MI.
- Repo changed ( `https://github.com/wso2/kubernetes-mi.git` to `https://github.com/wso2/helm-mi.git`)

Deploying micro integrator with helm

---

en/docs/reference/connectors/facebook-ads-connector/facebook-ads-configuration.md
en/docs/reference/connectors/facebook-ads-connector/facebook-ads-overview.md

$title
Related: https://github.com/wso2-extensions/esb-connector-facebookads/pull/2

Add facebook ads audience APIs

---

en/docs/reference/mediators/drop-mediator.md
en/docs/reference/mediators/respond-mediator.md
en/docs/reference/mediators/sequence-mediator.md

This PR is to update 
1. Drop mediator
2. Respond Mediator
3. Sequence Mediator
pages
> Link to the PR for changes to the …

Update drop, respond, and sequence mediator docs

---

en/docs/reference/connectors/snowflake-connector/snowflake-connector-reference.md

Changes included
- add `keepAlive` parameter information in the connector configuration section
Fixes #856

Update Snowflake Connector Reference Documentation

---

en/docs/reference/mediators/about-mediators.md
en/docs/reference/mediators/variable-mediator.md
en/mkdocs.yml

Add variable mediator docs
https://github.com/wso2/wso2-synapse/pull/2225

Add variable mediator docs

---

en/docs/reference/mediators/log-mediator.md

Update log mediator for 4.4.0 version
https://github.com/wso2/wso2-synapse/pull/2230

Update log mediator for 4.4.0 version

---

en/docs/reference/connectors/google-ads-connector/google-ads-configuration.md
en/docs/reference/connectors/google-ads-connector/google-ads-overview.md

This PR introduces an update to the documentation to reflect the recent improvements made to the `UploadUserData` operation and the addition of new getter operations. The documentation has been revised to include the following changes:  
1. **Updated Documentation for `UploadUserData`:**  
- Added detailed explanations on the new support for uploading user data as a JSON array.  
- Included information about the internal conversion of the JSON array into a [Google Ads API `UserData`](https://developers.google.com/google-ads/api/rest/reference/rest/v17/UserData) object.  
- Explained the normalization process for user identifiers and the supported formats (phone numbers, emails, mobile IDs, third-party user IDs, and address information).  
2. **Updated Documentation for Getter …

Update for UploadUserData Improvements and Getter Operations

---

en/docs/learn/examples/endpoint-examples/using-static-recepient-list-endpoints.md

This PR will fix the issue https://github.com/wso2/docs-mi/issues/805 by updating the scenario in the "How to Route Messages to a Static List of Recipients" documentation.

Update scenario for the Recipient-list endpoint

---

en/docs/reference/mediators/about-mediators.md
en/docs/reference/mediators/throw-error-mediator.md
en/mkdocs.yml

> Add ThrowError mediator docs
Related to wso2/product-micro-integrator/issues/3843

Add ThrowError mediator docs

---

en/docs/install-and-setup/setup/brokers/configure-with-rabbitmq.md

> $Subject
Fixes: #389
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Improve enabling SSL section in configure with RabbitMQ page

---

en/docs/reference/connectors/file-connector/file-connector-example.md

This PR is to fix a formatting error caused by an unclosed `<b>` tag, which resulted in all subsequent text appearing bold.

Fix formatting error

---

en/docs/reference/mediators/xslt-mediator.md

This PR is to add a note on optimizing the XSLT mediator.
Fixes https://github.com/wso2/docs-mi/issues/1217.

[4.3.0] Update xslt-mediator.md

---

en/docs/learn/examples/jms-examples/consuming-jms.md
en/docs/learn/examples/jms-examples/publish-subscribe-with-jms.md

Related: https://github.com/wso2/mi-vscode/issues/854
Fix the outdated usage of the endpoint mediator in https://mi.docs.wso2.com/en/4.4.0/learn/examples/jms-examples/consuming-jms/ and https://mi.docs.wso2.com/en/4.4.0/learn/examples/jms-examples/publish-subscribe-with-jms/ .

Fix outdated endpoint mediator usage in consuming-jms example

---

en/docs/assets/versions.json

The version dropdown is not shown due to a syntax issue in versions.json. This PR fixes the syntax issue

Fix version dropdown issue

---

en/docs/learn/samples/synapse-expressions.md
en/docs/reference/synapse-properties/expressions.md
en/docs/reference/synapse-properties/jsonpath-expressions.md
en/docs/reference/synapse-properties/rest-api-properties.md
en/docs/reference/synapse-properties/synapse-expressions-syntax.md
en/docs/reference/synapse-properties/synapse-expressions.md
en/docs/reference/synapse-properties/xpath-expressions.md
en/mkdocs.yml

1. Rename old expressions to legacy expressions.
2. Reduce search index for legacy expressions.
Fixes: https://github.com/wso2/docs-mi/issues/1464

Rename old expressions to legacy expressions

---

en/docs/assets/css/blue-palette-alt1.css
en/docs/assets/css/mitheme.css
en/docs/assets/js/mitheme.js
en/theme/material/base.html

Add page feedback option
Fixes: https://github.com/wso2/docs-mi/issues/1444

Add page feedback option

---

en/theme/material/base.html

Fix page feedback title issue. Append an empty `feedback.md` to auto populate the git issue title with the page name and url.

Fix page feedback title issue

---

en/docs/install-and-setup/setup/brokers/configure-with-rabbitmq.md
en/docs/install-and-setup/setup/performance-tuning/rabbitmq-transport-tuning.md
en/docs/reference/config-catalog-mi.md
en/docs/reference/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md

- Remove unused parameter `rabbitmq.server.retry.interval`
- Update connection pool size configs
Fixes: https://github.com/wso2/docs-mi/issues/1452

Update RabbitMQ config docs

---

en/docs/install-and-setup/setup/brokers/configure-with-rabbitmq.md
en/docs/install-and-setup/setup/performance-tuning/rabbitmq-transport-tuning.md
en/docs/reference/config-catalog-mi.md
en/docs/reference/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md

- Remove unused parameter `rabbitmq.server.retry.interval`
- Update connection pool size configs
Fixes: https://github.com/wso2/docs-mi/issues/1452

[420] Update RabbitMQ config docs

---

en/docs/install-and-setup/setup/brokers/configure-with-rabbitmq.md
en/docs/install-and-setup/setup/performance-tuning/rabbitmq-transport-tuning.md
en/docs/reference/config-catalog-mi.md
en/docs/reference/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md

- Remove unused parameter `rabbitmq.server.retry.interval`
- Update connection pool size configs
Fixes: https://github.com/wso2/docs-mi/issues/1452

[430] Update RabbitMQ config docs

---

en/docs/install-and-setup/setup/performance-tuning/rabbitmq-transport-tuning.md

Remove unused Rabbitmq props from example
https://github.com/wso2/docs-mi/issues/1503

Remove unused Rabbitmq props from example

---

en/docs/reference/connectors/file-connector/file-connector-config.md

> Update file connector configs with diskShareAccessMask

[4.3.0] Update file connector configs with diskShareAccessMask

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

Add a new guideline on restricting access to java classes and java methods/native objects in scripts that are used in script mediator. 
The updated section will appear as below.

Add documentation about restrict accessing to java classes and methods in script mediator

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

Add a new guideline on restricting access to java classes and java methods/native objects in scripts that are used in script mediator.
The updated section will appear as below.

Add documentation about restrict accessing to java classes and methods in script mediator for 4.3.0

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

Add a new guideline on restricting access to java classes and java methods/native objects in scripts that are used in script mediator.
The updated section will appear as below.

Add documentation about restrict accessing to java classes and methods in script mediator for 4.2.0
